/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Fri Sep 15 09:39:22 CST 2017
 */
package com.bosssoft.egov.asset.amc.user.mapper;

import org.apache.ibatis.annotations.Param;

import com.aspose.words.PageInfo;
import com.bosssoft.egov.asset.amc.user.model.AimsUserMain;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;
import com.bosssoft.platform.persistence.common.Mapper;
import com.bosssoft.platform.runtime.exception.BusinessException;

/**
 * 类说明:  Mapper接口（ Mapper层） .
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-09-15   BS　　　新建
 * </pre>

 */

public interface AimsUserMainMapper extends Mapper<AimsUserMain>{



/**
	 * 
	 * 查询分页.
	 *	`
	 * @param searcher 查询条件
	 * @param pageable 分页信息
	 * @return AimsUserMainPage列表
	 * @throws BusinessException 自定义异常
	 *
	 */
	public Page<AimsUserMain> queryAimsUserMainPage(@Param("searcher")Searcher searcher,@Param("page")PageInfo pageInfo);

	public void updateByUserCode(AimsUserMain aimsUserMain);
	
	public Page<AimsUserMain> queryShowTodoPage(@Param("searcher") Searcher searcher, @Param("page") Page<AimsUserMain> pageInfo);

}