/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sun Jan 22 13:27:10 CST 2017
 */
package com.bosssoft.egov.asset.template.service;

import java.util.List;

import com.bosssoft.egov.asset.template.entity.AimsTemplateModule;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;



/**
 * Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-22   Administrator　　　新建
 * </pre>
 */
public interface AimsTemplateModuleService {

/**
	 * 增加.
	 * 
	 * @param aimsTemplateModule 
	 */
	public void addAimsTemplateModule(AimsTemplateModule aimsTemplateModule);

	/**
	 * 删除及相关信息.
	 * 
	 * @param aimsTemplateModule 
	 */
	public void delAimsTemplateModule(AimsTemplateModule aimsTemplateModule);

	/**
	 * 修改.
	 * 
	 * @param aimsTemplateModule 
	 */
	public void updateAimsTemplateModule(AimsTemplateModule aimsTemplateModule);

	/**
	 * 获取列表.
	 * 
	 */
	public List<AimsTemplateModule> getAimsTemplateModuleList(AimsTemplateModule aimsTemplateModule);




   	/**
	 * 获取分页.
	 * 
		 */
	public Page<AimsTemplateModule> queryAimsTemplateModulePage(Searcher searcher, Page<AimsTemplateModule> page);
			
    /**
     * <p>函数名称：loadModuleTree        </p>
     * <p>功能说明：根据模板ID加载模块树
     *
     * </p>
     *<p>参数说明：</p>
     * @param modulePid 模板ID
     * @return
     *
     * @date   创建时间：2017年1月22日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public List<AimsTemplateModule> loadModuleTree(Long modulePid);

    /**
     * <p>函数名称： searchListByKey       </p>
     * <p>功能说明：左侧树节点查询
     *
     * </p>
     *<p>参数说明：</p>
     * @param _key
     * @return
     *
     * @date   创建时间：2017年11月7日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
     */
    public List<AimsTemplateModule> searchListByKey(String _key);
}
 