/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sun Jan 22 13:27:50 CST 2017
 */
package com.bosssoft.egov.asset.template.service;

import java.util.List;
import java.util.Map;

import com.bosssoft.egov.asset.template.entity.AimsTemplateDetail;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;



/**
 * Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-22   Administrator　　　新建
 * </pre>
 */
public interface AimsTemplateDetailService {

/**
	 * 增加.
	 * 
	 * @param aimsTemplateDetail 
	 */
	public Map<String, Object> addAimsTemplateDetail(AimsTemplateDetail aimsTemplateDetail);

	/**
	 * 删除及相关信息.
	 * 
	 * @param aimsTemplateDetail 
	 */
	public Map<String, Object> delAimsTemplateDetail(AimsTemplateDetail aimsTemplateDetail);

	/**
	 * 修改.
	 * 
	 * @param aimsTemplateDetail 
	 */
	public Map<String, Object> updateAimsTemplateDetail(AimsTemplateDetail aimsTemplateDetail);

	/**
	 * 获取列表.
	 * 
	 */
	public List<AimsTemplateDetail> getAimsTemplateDetailList(AimsTemplateDetail aimsTemplateDetail);




   	/**
	 * 获取分页.
	 * 
		 */
	public Page<AimsTemplateDetail> queryAimsTemplateDetailPage(Searcher searcher, Page<AimsTemplateDetail> page);
			
    /**
     * <p>函数名称：queryTemplateDetailPage        </p>
     * <p>功能说明：根据模板ID和单位ID获取模板列表
     *
     * </p>
     *<p>参数说明：</p>
     * @param searcher
     * @param page
     * @param moduleId
     * @param orgId
     * @return
     *
     * @date   创建时间：2017年3月3日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public Page<AimsTemplateDetail> queryTemplateDetailPage(Searcher searcher, Page<AimsTemplateDetail> page, Long moduleId,
    		Long orgId);

    /**
     * <p>函数名称：saveTemplateFile        </p>
     * <p>功能说明：上传模板文件
     *
     * </p>
     *<p>参数说明：</p>
     * @param moduleItemId  模板ID
     * @param templateFile  模板文件 
     * @param fileName      文件名
     * @return
     *
     * @date   创建时间：2017年2月14日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public Map<String, Object> saveTemplateFile(Long moduleItemId,byte[] templateFile, String fileName);
    
    /**
     * <p>函数名称：queryOne        </p>
     * <p>功能说明：根据模板ID查询模板信息
     *
     * </p>
     *<p>参数说明：</p>
     * @param moduleItemId
     * @return
     *
     * @date   创建时间：2017年2月14日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public AimsTemplateDetail queryOne(Long moduleItemId);
    
    /**
     * <p>函数名称：queryOneByFileName        </p>
     * <p>功能说明：根据文件名查询模板信息(在进行前端模板版本号控制时需要用到)
     *
     * </p>
     *<p>参数说明：</p>
     * @param fileName 文件名
     * @return
     *
     * @date   创建时间：2017年2月22日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public AimsTemplateDetail queryOneByFileName(String fileName);
    
    /**
     * <p>函数名称：queryDefaultTemplate        </p>
     * <p>功能说明：查询默认模板
     *
     * </p>
     *<p>参数说明：</p>
     * @param moduleId
     * @return
     *
     * @date   创建时间：2017年11月7日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
     */
    public AimsTemplateDetail queryDefaultTemplate(Long moduleId);
    
    /**
     * <p>函数名称：select        </p>
     * <p>功能说明：查询打印模板信息
     *
     * </p>
     *<p>参数说明：</p>
     * @param aimsTemplateDetail
     * @return
     *
     * @date   创建时间：2017年11月3日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
     */
    public List<AimsTemplateDetail> select(AimsTemplateDetail aimsTemplateDetail);
    
    /**
     * <p>函数名称：queryTemplateDetailPageByOrgId        </p>
     * <p>功能说明：根据单位id和模板id获取分页信息
     *
     * </p>
     *<p>参数说明：</p>
     * @param searcher
     * @param page
     * @param moduleId
     * @param orgId
     * @return
     *
     * @date   创建时间：2017年11月7日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
     */
    public Page<AimsTemplateDetail> queryTemplateDetailPageByOrgId(Searcher searcher,
			Page<AimsTemplateDetail> page, Long moduleId, Long orgId);
}
 