/**
 * * Auto generated by Bossssoft Studio version 1.0 beta
 * Wed Nov 09 16:30:51 CST 2016
 */
//define(['引入外部js模块或控件'],function('引入外部js或控件的别名'){})
define(
		[ 
		  "app/widgets/window/app-dialog",
		  "app/app-pagebase","resources/egov/js/asset/workorder/assetworkorder_add.js",
		  "resources/egov/js/common/utils/StatusUtils",
		  "resources/egov/js/asset/template/BsNetFun.js"],
		function(Dialog,PageBase,dlg,$status,BsNetFun) {	
		   var AssetWorkorderModel = PageBase.extend({
		             //类初始化
		            initialize : function() {
						AssetWorkorderModel.superclass.initialize.call(this);
					},
					REFRESH_FLAG:false,//用于判断关闭页面后是否要执行插传入的回调方法
					//控件监听事件  格式：#控件id#:{事件名:事件方法}
					listeners:{
						//查看按钮事件 
						assetWorkorderPage_btnView:{
							click: function () {
                                var _self = AssetWorkorderModel.getInstance();			                   			         
			                    
			                    var rows = $("#assetWorkorderPage_grid").grid("getSelections");
			 
			                    if (rows == null || rows.length <= 0) {
			                    	$A.assetMsg.warn("请选择要查看的单据！");			            
			                        return;
			                    } else if (rows.length > 1) {
			                    	$A.assetMsg.warn("修改单据不能选中多条数据！");			               
			                        return;
			                    } else {
			                    	_self.showViewPage(rows[0]);			           
			                    }	
							}
						},
						
						//修改按钮事件
						assetWorkorderPage_btnEdit: {
			                click: function () {
			                    var _self = AssetWorkorderModel.getInstance();			                   			         
			                    
			                    var rows = $("#assetWorkorderPage_grid").grid("getSelections");
			 
			                    if (rows == null || rows.length <= 0) {
			                    	$A.assetMsg.warn("请选择要修改的单据！");			            
			                        return;
			                    } else if (rows.length > 1) {
			                    	$A.assetMsg.warn("修改单据不能选中多条数据！");			               
			                        return;
			                    } else {
			                    	_self.showEditPage(rows[0]);			           
			                    }
			                }
			            },
			          //关闭
			            aimsDisposePage_btnExit:{
							click:function(){
								$.closeCurrentTab();
							}
						},
						//刷新数据
						aimsDisposePage_btnRefresh:{
							click:function(){
			                    AssetWorkorderModel.getInstance().refreshData();	
							}
						},												
						//删除事件
						assetWorkorderPage_btnDelete:{
							click:function(){	
							 var $data = $("#assetWorkorderPage_grid").grid('getSelections');	
							 if ($data.length<1){
								 $A.assetMsg.warn('请选择要删除的单据！');
								return;
							}							
						  // 新批删除（暂存的数据直接删除，>=9不能进行物理删除，标识为3）
						  $A.messager.confirm("确认删除选中的单据！", {
							  okCall: function(){
								  AssetWorkorderModel.getInstance().batchDelete($data);
							  }
						  })
						}
					   },
					    //新增按钮事件  
					   assetWorkorderPage_btnAdd:{
							click: function(){
							dlg.showPage(dlg.ACTION.ADD,null,function(){ //
								 AssetWorkorderModel.getInstance().refreshData();
							});																																						
						 }
						},						

						//网格选择数据事件
						assetWorkorderPage_grid:{
							 //网格双击事件						
			               onDblClickRow: function (rowData, rowIndex) {
			            	   var _self = AssetWorkorderModel.getInstance();
			                	//_self.showEditPage(rowData);
			            	   _self.showEditPage(rowData);
			                },	
			                onSelect:function(selectedRowData,Row){
								var billId = selectedRowData.billId;
								var billCode = selectedRowData.billCode;
								if (billCode==null)
									billCode="";
								var url="egov/asset/workorder/getAimsWorkOrder.do";
									$app.ajax.ajaxCall({
										url : url,
										data :{billId:billId},
										callback : function(data) {
										}
								});								
							},							  
						},
									
						disposeType:{
							onChange:function(){
								$a('#aimsDisposePage_query').xquery('quickQuery');
							}
						},
					},
					getReportObject:function(){
						var obj = {
								username:'FujianBossSoftwareDevelopmentCoLtd',
								serialNo:'ARWB9RLDN5GJDP5AP2B9BCHG3ANI75WFUR9BAWQ9C3Q75AFLR9L0UI514YD4B8XQ93Y2L92RP798RWQ9ICJ78LKAX4'	
						}; 
						var Report = document.getElementById("BosssoftReport");
						Report.Register(obj.username, obj.serialNo);
						return Report;
					},				
					//页面加载后初始化
					initPage:function(data){							
						//$A('#assetType6CodeMain').textbox('setValue',assetType6Code);
						//$A("#aimsDisposePage_grid").grid('setFixedParameter',{assetType6Code:assetType6Code});
						//$A("#bizStatus").textbox('setValue','');
						//$A('#bizStatusName').combobox('setValue','1');
						//$A('#bizStatusName').combobox('setText','暂存');						
						
						$A("#aimsDisposePage_query").xquery("toggle");
						$A("#aimsDisposePage_query").xquery("quickQuery");
					},
					//显示查看业
					showViewPage:function(data,e){
					    var _self=this;
						dlg.showPage(dlg.ACTION.VIEW,data,function(){
							AssetWorkorderModel.getInstance().refreshData(); 
						});
					},
	
					refreshData:function(){					
						$("#assetWorkorderPage_grid").grid("reload");
					},
													
					//新批删除
					batchDelete:function(data){
						var $params = {};
						var billCodeList="";

						$A.showWaitScreen("正在删除单据...");
						$params['aimsWorkOrder'] = JSON.stringify(data);
						var url = "egov/asset/workorder/batchDelete.do";
						$app.ajax.ajaxCall({
							url : url,
							data : $params,
							callback : function() {
								AssetWorkorderModel.getInstance().refreshData();			
								$A.assetMsg.success('删除成功！');	
								$A.hideWaitScreen();
								$A("#assetWorkorderPage_grid").grid('unselectAll');
							},
						   error:function(){
	                    	 $A.hideWaitScreen();	 
	                       }
						});	
					},
					
					//显示编辑业
					showEditPage:function(data1,e){				
						var bizStatus;
						var billStatus;
						var billId = data1.billId;
						var url="egov/asset/workorder/getAimsWorkOrder.do";
							$app.ajax.ajaxCall({
								url : url,
								data :{billId:billId},
								callback : function(data) {
									bizStatus = data.bizStatus;
									billStatus = data.billStatus;
									var action=dlg.ACTION.EDIT;
									
									if (bizStatus>=10){	
										action=dlg.ACTION.VIEW;
										//$A.assetMsg.warn('审核单据只能查看！');
									};									
									var _self=this;
									dlg.showPage(action,data,function(){  
										AssetWorkorderModel.getInstance().refreshData(); //_self
									});
								}
						});
							
					},
					doDeleteData:function(data,e){
						 var _self=this;
						 $A.assetMsg.confirm("确认删除当前记录吗？", {
							ok : function() {
								AssetWorkorderModel.getInstance().batchDelete(data);																																																			
							}
						});
					},
														
					//控件属性重置
					initUIExtConfig : function() {
					    var _self=this;
						this.uiExtConfig={
							//格式 #控件id#:function(控件属性集类){ config.setAttr("控件属性名","属性值"),// 网格，下拉网格，特殊设置config.getColumn("网列id").setAttr("列属性名","列属性值")config.getButton("网格内包含的按钮id").setAttr("handler","点击事件")  }
								assetWorkorderPage_grid:function(config){
								
								config.getButton("assetWorkorderPage_grid_btnEdit").setAttr("handler",_self.showEditPage);
								config.getButton("assetWorkorderPage_grid_btnView").setAttr("handler",_self.showViewPage);
								config.getButton("assetWorkorderPage_grid_btnDel").setAttr("handler",_self.doDeleteData);
							}						
						}	
					},					
		 });
		 AssetWorkorderModel.getInstance=function(){
		     if (!this.instance){
		    	 this.instance =new AssetWorkorderModel();
		     }
		     return this.instance;
		 }
		
		 return  AssetWorkorderModel.getInstance();
	   })