/*******************************************************************************
 * 福建博思软件1997-2017 版权所有
 * 
 * Auto generated by Bosssoft Studio version 1.0 beta
 * 2018年1月31日下午4:38:12
 *******************************************************************************/
package com.bosssoft.egov.asset.utils;

import java.io.IOException;

import com.bosssoft.egov.asset.common.util.StringUtilsExt;
import com.bosssoft.egov.asset.skin.entiry.AssetSkinCfg;
import com.bosssoft.egov.asset.skin.service.AssetSkinCfgService;
import com.bosssoft.platform.runtime.spring.RuntimeApplicationContext;

/**
 * @ClassName	类名：AssetExtServiceUtils.java
 * @Description	功能说明：ext服务工具
 * <pre>
 * @date		创建日期：2018年1月31日
 * @author		创建人：chenzhibin
 * @version		版本号：V1.0
 * <pre>
 *-------------------修订记录---------------------
 */
public class AssetExtServiceUtils {

	/**
	 * <p>功能说明：获取皮肤配置服务
	 * </p>
	 * <p>参数说明：
	 * @return
	 * </p>
	 *
	 * @date	创建时间：2018年1月31日
	 * @author	作者：chenzhibin
	 */
	public static AssetSkinCfgService getSkinCfgService(){
		AssetSkinCfgService bean = (AssetSkinCfgService) RuntimeApplicationContext.getBean(AssetSkinCfgService.class);
		return bean;
	}
	
	public static String getSkinCfg() throws IOException{
		AssetSkinCfgService skinCfgService = AssetExtServiceUtils.getSkinCfgService();
		AssetSkinCfg skin = skinCfgService.getSkinCfg();
		return skin == null || StringUtilsExt.isBlank(skin.getSkinName()) ? "default" : skin.getSkinName();
	}
}
