/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * 2017年10月25日 下午3:31:06
 */
package com.bosssoft.egov.asset.ext.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.bosssoft.egov.asset.ext.entity.AssetGridColCfg;
import com.bosssoft.egov.asset.ext.mapper.AssetGridColCfgMapper;
import com.bosssoft.egov.asset.ext.service.AssetGridColCfgService;

/**
 * 类说明:
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017年10月25日  chenzhibin  新建
 * </pre>
 */
@Service
public class AssetGridColCfgServiceImpl implements AssetGridColCfgService {
	
	@Autowired
	private AssetGridColCfgMapper gridColCfgMapper;

	@Override
	public List<AssetGridColCfg> getGridColCfgByGridCfgId(Long gridCfgId) {
		return gridColCfgMapper.getGridColCfgByGridCfgId(gridCfgId);
	}

}
