/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sun Jan 22 17:20:52 CST 2017
 */
package com.bosssoft.egov.asset.dispatch.service;

import com.bosssoft.egov.asset.dispatch.entity.AssetDispatchMonitorTask;


/**
 * 调度-作业配置表Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-22   Administrator　　　新建
 * </pre>
 */
public interface QuartzDispatchTaskJobService {

	public void addTaskJob(String taskId);
	
	public void addAllEnableJob();

	public void removeTaskJob(String taskId);

	public void modifyTaskJob(AssetDispatchMonitorTask record);
	
	public void stopTaskJob(String taskId);
	
	public void resumeTaskJob(String taskId);
}
