/*******************************************************************************
 * 福建博思软件1997-2017 版权所有
 * 
 * Auto generated by Bosssoft Studio version 1.0 beta
 * 2017年12月29日上午10:18:22
 *******************************************************************************/
package com.bosssoft.egov.asset.ext.service;

import com.bosssoft.egov.asset.ext.entity.AssetGridQueryHistory;
import com.bosssoft.egov.asset.ext.utils.AssetGridExtCacheUtil;
import com.bosssoft.platform.runtime.web.response.AjaxResult;

/**
 * @ClassName	类名：AssetGridQueryHistoryService.java
 * @Description	功能说明：网格查询历史记录service接口
 * <pre>
 * @date		创建日期：2017年12月29日
 * @author		创建人：chenzhibin
 * @version		版本号：V1.0
 * <pre>
 *-------------------修订记录---------------------
 */
public interface AssetGridQueryHistoryService {
	/**
	 * 
	 * <p>功能说明：获取网格历史查询记录<br>
	 * 根据userCode、gridId、bizType获取相应网格查询历史记录
	 * </p>
	 * <p>参数说明：
	 * @param history
	 * @return 返回查询列表
	 * </p>
	 *
	 * @date	创建时间：2017年12月29日
	 * @author	作者：chenzhibin
	 */
	AssetGridExtCacheUtil<AssetGridQueryHistory> getGridQueryHistory(AssetGridQueryHistory history);

	/**
	 * 
	 * <p>功能说明：保存历史查询记录<br>
	 * 新增或更新查询记录
	 * </p>
	 * <p>参数说明：
	 * @param history
	 * @param type 操作类型，ADD：新增、UPDATE：更新
	 *  
	 * @return 返回AjaxResult
	 * </p>
	 *
	 * @date	创建时间：2017年12月29日
	 * @author	作者：chenzhibin
	 */
	AjaxResult saveQueryHistory(AssetGridQueryHistory history);

	/**
	 * <p>功能说明：清空历史查询记录
	 * </p>
	 * <p>参数说明：
	 * @param history
	 * @return
	 * </p>
	 *
	 * @date	创建时间：2017年12月29日
	 * @author	作者：chenzhibin
	 */
	AjaxResult clearQueryHistory(AssetGridQueryHistory history);

}
