/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Tue Jul 18 17:04:19 CST 2017
 */
package com.bosssoft.egov.asset.deprtiming.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bosssoft.egov.asset.deprtiming.entity.AimsDeprTiming;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;
import com.bosssoft.platform.persistence.common.Mapper;
import com.bosssoft.platform.runtime.exception.BusinessException;

/**
 * 类说明: 折旧定时配置接口（ Mapper层） .
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * Linxt　　　新建
 * </pre>

 */

public interface AimsDeprTimingMapper extends Mapper<AimsDeprTiming>{



/**
	 * 
	 * 查询打印模版取数表分页.
	 *	`
	 * @param searcher 查询条件
	 * @param pageable 分页信息
	 * @return AimsDeprTimingPage列表
	 * @throws BusinessException 自定义异常
	 *
	 * <pre>
	 * 修改日期　　　修改人　　　修改原因
     *   Linxt　　　新建
	 * </pre>
	 */
	public Page<AimsDeprTiming> queryAimsDeprTimingPage(@Param("searcher")Searcher searcher,@Param("page")Page<AimsDeprTiming> page);

	public List<AimsDeprTiming> queryByOrgCode(@Param("orgCode") String orgCode);
	
	
	public AimsDeprTiming queryOne(@Param("id")Long id);
	
	public AimsDeprTiming queryByOrgId(@Param("orgId") Long orgId);
	
	/**
	 * 修改
	 * @param aims
	 * @return
	 */
	public int updateByOrgCode(AimsDeprTiming aimsDeprTiming);
	
	/**
	 * 删除
	 * @param aimsDeprTiming
	 * @return
	 */
	public int deleteByOrgCode(AimsDeprTiming aimsDeprTiming);
	/**
	 * 根据id删除
	 * @param aimsDeprTiming
	 * @return
	 */
	public int deleteById(Long id);
	
}