/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Mon Jan 09 14:25:42 CST 2017
 */
package com.bosssoft.egov.asset.deprtiming.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.bosssoft.egov.asset.deprtiming.entity.DeprConfig;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;
import com.bosssoft.platform.persistence.common.Mapper;
import com.bosssoft.platform.runtime.exception.BusinessException;

/**
 * 类说明:  Mapper接口（ Mapper层） .
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * </pre>

 */

public interface DeprConfigMapper extends Mapper<DeprConfig>{



/**
	 * 
	 * 查询分页.
	 *	`
	 * @param searcher 查询条件
	 * @param pageable 分页信息
	 * @return AimsDeprConfigPage列表
	 * @throws BusinessException 自定义异常
	 *
	 */
	public Page<DeprConfig> queryAimsDeprConfigPage(@Param("searcher")Searcher searcher,@Param("page")Page<DeprConfig> page);
			
	/**
	 * <p>函数名称：queryOneByOrgId        </p>
	 * <p>功能说明：根据单位ID和资产分类查询折旧配置
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param orgId
	 * @param assetType6Code 资产分类
	 * @return
	 *
	 */
	public DeprConfig queryOneByOrgId(@Param("orgId") Long orgId, @Param("assetType6Code") String assetType6Code);
	
	public DeprConfig queryOneByCondition(@Param("condition") String condition,@Param("params")Map<String,Object> params);

	/**
	 * <p>函数名称：updateById        </p>
	 * <p>功能说明：修改折旧配置
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param aimsDeprConfig
	 *
	 */
	public void updateById(DeprConfig aimsDeprConfig);
	
	/**
	 * 
	 * <p>函数名称：  queryConfigGroup      </p>
	 * <p>功能说明：获取所有信息
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @return
	 */
	public List<DeprConfig> queryAllConfig();
}