/**
 * * Auto generated by Bossssoft Studio version 1.0 beta Fri Nov 18 17:20:59 CST
 * 2016
 */
// define(['引入外部js模块或控件'],function('引入外部js或控件的别名'){})
define(["app/app-pagebase"],
	function(PageBase){
		var AmcUserUtil= PageBase.extend({		 
			//设置表单样式，主要用于设置表单不可编辑
			setFormFieldStyle:function($input){
			    	var len = $input.length;
		   		    for (var i=0;i<len;i++){
			   			 var options = $($input[i]).attr('_options');
						 if(options){
							 var obj = eval('(' + options + ')');
							 obj['readonly']='true';
							 var s = JSON.stringify(obj);
							 $($input[i]).attr('_options',s).addClass('form-field-view');
						 }else{
							 $($input[i]).attr('_options','{readonly:true}').addClass('form-field-view');
						 }
		   		    }		 
			},
			 
			initPage:function(){
				
			},
			
		});
		

		
		
		AmcUserUtil.getInstance=function(){
		     if (!this.instance){
		    	 this.instance =new AmcUserUtil();
		     }
		     return this.instance;
		 }
		return  AmcUserUtil.getInstance();
	   })
	   
	   
	   
	   
