/**
 * * Auto generated by Bossssoft Studio version 1.0 beta Sun Sep 18 11:45:38 CST
 * 2016
 */
// define(['引入外部js模块或控件'],function('引入外部js或控件的别名'){})
define([ "app/widgets/window/app-dialog", "app/app-pagebase",
		 "resources/egov/js/asset/amcuser/amcuser_modify.js","resources/egov/js/asset/amcuser/amcuser_resetpassword.js"],
				function(Dialog, PageBase, modify, reset) {
			var AmcUserModel = PageBase.extend({
						// 类初始化
						initialize : function() {
							AmcUserModel.superclass.initialize.call(this);
						},
						
						isNeedAudit:null,
						// 控件监听事件 格式：#控件id#:{事件名:事件方法}
						listeners : {
							//查询框变化监听事件
							Code:{
								onChange:function(newVal,oldVal){
									$A("#amcUserPage_query").xquery("quickQuery");
								}
							},
							//
							Name:{
								onChange:function(newVal,oldVal){
									$A("#amcUserPage_query").xquery("quickQuery");
								}
							},
							//
							mobileNo:{
								onChange:function(newVal,oldVal){
									$A("#amcUserPage_query").xquery("quickQuery");
								}
							},
							//
							org:{
								onChange:function(newVal,oldVal){
									$A("#amcUserPage_query").xquery("quickQuery");
								}
							},
							
							status:{
								onChange:function(newVal,oldVal){
									$A("#amcUserPage_query").xquery("quickQuery");
								}
							},
							//网格监听事件
							amcUserPanelUserdetails:{
								onDblClickRow:function(rowData, rowIndex){
									var self = AmcUserModel.getInstance();
									var isNeedAudit = self.isNeedAudit;
									var userCode = rowData.userCode;
									/*modify.showUserInfo({toDoStatus:modify.ACTION.EDIT,userCode:userCode},function(){
										AmcUserModel.getInstance().refreshData();
									});*/
									modify.showUserInfo({toDoStatus:modify.ACTION.EDIT,userCode:userCode,isNeedAudit:isNeedAudit},function(){
										AmcUserModel.getInstance().refreshData();
									});
								}
							},
							
							//新增按钮事件
							amcUserPanel_add : {
								click : function() {
									var self = AmcUserModel.getInstance();
									var isNeedAudit = self.isNeedAudit;
									modify.showUserInfo({toDoStatus:modify.ACTION.ADD,userCode:"",isNeedAudit:isNeedAudit},function(){
										AmcUserModel.getInstance().refreshData();
									});
								}
							},
							//重置密码按钮事件
							amcUserPanel_reset: {
								click:function() {
									var rows = $('#amcUserPanelUserdetails').grid('getSelections');
									if(rows == null || rows.length == 0){
										$A.assetMsg.warn("请选择需要重置密码的网格行！");
										return;
									}
									reset.showPage(null,rows[0],function(){
										AmcUserModel.getInstance().refreshData();
									});
								}
							},
							//4、批量删除按钮
							amcUserPanel_del : {
								click : function() {
									var self = AmcUserModel.getInstance();
									var isNeedAudit = self.isNeedAudit;
									var rows = $('#amcUserPanelUserdetails').grid('getSelections');
									if (rows == null || rows.length == 0) {
										$a.assetMsg.error("请选择数据");
										return false;
									} else {									
										//在后端判断用户信息是否在流程中
										$a.assetMsg.confirm("确认删除选中的用户吗？",
										{
											okCall : function() {
												var url = "egov/asset/amcuser/batchDeleteUsers.do";
												$app.ajax.ajaxCall({
													url : url,
													data : {
														"amcUsers": JSON.stringify(rows),
														isNeedAudit: isNeedAudit
													},
													callback : function(data) {
														if(data.tag == true){
															$A.assetMsg.success(data.msg);
															$('#amcUserPanelUserdetails').grid('reload');
														}else{
															$A.assetMsg.warn(data.msg);
															$('#amcUserPanelUserdetails').grid('reload');
														}
													}
												});
											}
										});
									}
								}
							}
						},
						//重置密码
						resetUserPs:function(data, e){
							reset.showPage(null,data,function(){
								AmcUserModel.getInstance().refreshData();
							});
						},
						//打开更新主机构页面
						updateSubOrg : function(data,e) {
							var userCode = data.userCode;
							/*modify.showUserInfo({toDoStatus:modify.ACTION.EDIT,userCode:userCode},function(){
								AmcUserModel.getInstance().refreshData();
							});*/
							var self = AmcUserModel.getInstance();
							var isNeedAudit = self.isNeedAudit;
							modify.showUserInfo({toDoStatus:modify.ACTION.EDIT,userCode:userCode,isNeedAudit:isNeedAudit},function(){
								AmcUserModel.getInstance().refreshData();
							});
						},
						beforePageInit:function(page,data){
							var self = AmcUserModel.getInstance();
							//返回一个isNeedAudit参数，用来判断是否要走审核流程
							self.isNeedAudit = data.isNeedAudit;
						},
						// 页面加载后初始化
						initPage : function() {
							//加载查询框 状态下拉列表
							var url = "platform/appframe/dicthelper/getUserStatus.do";
							$app.ajax.ajaxCall({
								url : url,
								callback : function(json) {
									$A("#status").combobox("loadData",json);
								}
							});
						},
						//表格里头的删除按钮
						doDeleteData : function(data, e) {
							var _self = AmcUserModel.getInstance();
							var isNeedAudit = _self.isNeedAudit;
							var userId = data.userId;
							var userCode = data.userCode;
							var userName = data.userName;
							$a.assetMsg.confirm("确认删除该用户？",
									{
										okCall : function() {
											var url = "egov/asset/amcuser/doDelete.do";
											$app.ajax.ajaxCall({
												url : url,
												data : {
													userId: userId,
													userCode: userCode,
													userName: userName,
													isNeedAudit: isNeedAudit
												},
												callback : function(data) {
													if(data.tag == true){
														$A.assetMsg.success(data.msg);
														$('#amcUserPanelUserdetails').grid('reload');
													}else{
														$A.assetMsg.warn(data.msg);
														$('#amcUserPanelUserdetails').grid('reload');
													}
												}
											});
										}
									});
						},

						// 控件属性重置
						initUIExtConfig : function() {
							var _self = this;
							this.uiExtConfig = {
								amcUserPanelUserdetails : function(config) {
									config.getButton("amcUserPanel_grid_btnReset").setAttr("handler",_self.resetUserPs);
									config.getButton("amcUserPanel_grid_btnOrg").setAttr("handler",_self.updateSubOrg);
									config.getButton("amcUserPanel_grid_btnDel").setAttr("handler",_self.doDeleteData);
								}

							}
						}

					});
			AmcUserModel.getInstance = function() {
				if (!this.instance) {
					this.instance = new AmcUserModel();
				}
				return this.instance;
			}

			return AmcUserModel.getInstance();
		})