/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Mon Jan 16 13:07:41 CST 2017
 */
package com.bosssoft.egov.asset.monitor.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.bosssoft.egov.asset.monitor.entity.FabMonitorRecord;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.persistence.common.Mapper;
import com.bosssoft.platform.common.lang.data.Searcher;
import com.bosssoft.platform.runtime.exception.BusinessException;

/**
 * 类说明: 预警记录表 Mapper接口（ Mapper层） .
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-16   jinbiao　　　新建
 * </pre>
 */

public interface FabMonitorRecordMapper extends Mapper<FabMonitorRecord> {

	/**
	 * 
	 * 查询预警记录表分页. `
	 * 
	 * @param searcher
	 *            查询条件
	 * @param pageable
	 *            分页信息
	 * @return FabMonitorRecordPage列表
	 * @throws BusinessException
	 *             自定义异常
	 *
	 */
	public Page<FabMonitorRecord> queryFabMonitorRecordPage(@Param("searcher") Searcher searcher, @Param("page") Page<FabMonitorRecord> page);

	public List<FabMonitorRecord> queryList(@Param("searcher")Searcher searcher,@Param("sortProperty")String sortProperty,@Param("sortDirection")String sortDirection);

	public Integer queryCount(@Param("searcher")Searcher searcher);
	
    /**
     * 查询记录统计
     * @param searcher
     * @param page
     * @return
     */
	public Page<Map<String, Object>> queryRecordCountData(@Param("searcher")Searcher searcher,	@Param("page")Page<FabMonitorRecord> page);
	
	public List<FabMonitorRecord> queryRecordByType(@Param("searcher")Searcher searcher ,@Param("types")String types);

	public List<FabMonitorRecord> getFabMonitorRecordEvtName(@Param("searcher")Searcher searcher ,@Param("morgCode")String morgCode);

}