/**
 * 福建博思软件 1997-2018 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Fri Jan 12 18:51:41 CST 2018
 */
package com.bosssoft.egov.asset.drc.entity;
import javax.persistence.Column;
import javax.persistence.Table;

/**
 * 用户对应角色不显示菜单信息表对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2018-01-12   xiedeshou　　　新建
 * </pre>
 */
 @Table(name = "DRC_AUTH_MENU_USER")
public class DrcAuthMenuUser implements java.io.Serializable {

	private static final long serialVersionUID = 180112185448591L;
	
	// Fields
	
	/**
	 * .
	 */
    @Column(name = "ID")
	private Long id;
	/**
	 * 用户id.
	 */
    @Column(name = "USER_ID")
	private String userId;
	/**
	 * 用户编码.
	 */
    @Column(name = "USER_CODE")
	private String userCode;
	/**
	 * 用户名称.
	 */
    @Column(name = "USER_NAME")
	private String userName;
	/**
	 * 角色id.
	 */
    @Column(name = "ROLE_ID")
	private String roleId;
	/**
	 * 角色编码.
	 */
    @Column(name = "ROLE_CODE")
	private String roleCode;
	/**
	 * 角色名称.
	 */
    @Column(name = "ROLE_NAME")
	private String roleName;
	/**
	 * 应用ID.
	 */
    @Column(name = "APP_ID")
	private String appId;
	/**
	 * 菜单id.
	 */
    @Column(name = "MENU_ID")
	private String menuId;
	/**
	 * 菜单编码.
	 */
    @Column(name = "MENU_CODE")
	private String menuCode;
	/**
	 * 菜单名称.
	 */
    @Column(name = "MENU_NAME")
	private String menuName;
	/**
	 * 状态.
	 */
    @Column(name = "STATUS")
	private String status;
	/**
	 * 备注.
	 */
    @Column(name = "REMARK")
	private String remark;
	
	// Constructors
 
    /** default constructor */
	public DrcAuthMenuUser() {
	}

	/**
	 * .
	 * @return
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * .
	 * @param id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * 用户id.
	 * @return
	 */
	public String getUserId() {
		return this.userId;
	}

	/**
	 * 用户id.
	 * @param userId
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * 用户编码.
	 * @return
	 */
	public String getUserCode() {
		return this.userCode;
	}

	/**
	 * 用户编码.
	 * @param userCode
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	/**
	 * 用户名称.
	 * @return
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * 用户名称.
	 * @param userName
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * 角色id.
	 * @return
	 */
	public String getRoleId() {
		return this.roleId;
	}

	/**
	 * 角色id.
	 * @param roleId
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * 角色编码.
	 * @return
	 */
	public String getRoleCode() {
		return this.roleCode;
	}

	/**
	 * 角色编码.
	 * @param roleCode
	 */
	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	/**
	 * 角色名称.
	 * @return
	 */
	public String getRoleName() {
		return this.roleName;
	}

	/**
	 * 角色名称.
	 * @param roleName
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * 应用ID.
	 * @return
	 */
	public String getAppId() {
		return this.appId;
	}

	/**
	 * 应用ID.
	 * @param appId
	 */
	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
	 * 菜单id.
	 * @return
	 */
	public String getMenuId() {
		return this.menuId;
	}

	/**
	 * 菜单id.
	 * @param menuId
	 */
	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	/**
	 * 菜单编码.
	 * @return
	 */
	public String getMenuCode() {
		return this.menuCode;
	}

	/**
	 * 菜单编码.
	 * @param menuCode
	 */
	public void setMenuCode(String menuCode) {
		this.menuCode = menuCode;
	}

	/**
	 * 菜单名称.
	 * @return
	 */
	public String getMenuName() {
		return this.menuName;
	}

	/**
	 * 菜单名称.
	 * @param menuName
	 */
	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	/**
	 * 状态.
	 * @return
	 */
	public String getStatus() {
		return this.status;
	}

	/**
	 * 状态.
	 * @param status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * 备注.
	 * @return
	 */
	public String getRemark() {
		return this.remark;
	}

	/**
	 * 备注.
	 * @param remark
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

}