/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Mon Jan 09 09:43:31 CST 2017
 */
package com.bosssoft.egov.asset.drc.entity;
import javax.persistence.Column;
import javax.persistence.Table;

/**
 * 数据权限规则表对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-09   Administrator　　　新建
 * </pre>
 */
 @Table(name = "DRC_AUTH_RULE")
public class DrcAuthRule implements java.io.Serializable {

	private static final long serialVersionUID = 170109094447255L;
	
	// Fields
	
	/**
	 * .
	 */
    @Column(name = "ID")
	private Long id;
	/**
	 * 所属配置id预留 暂时不用.
	 */
    @Column(name = "CFG_ID")
	private Long cfgId;
	/**
	 * 规则类型：org user 等 org时 登录时会切换单位信息.
	 */
    @Column(name = "RULE_TYPE")
	private String ruleType;
	/**
	 * 字段名称.
	 */
    @Column(name = "RULE_FIELD")
	private String ruleField;
	/**
	 * 字段值.
	 */
    @Column(name = "RULE_VALUE")
	private String ruleValue;
	/**
	 * 操作类型：= <>  > < 等 为空 默认=.
	 */
    @Column(name = "RULE_OPERATOR")
	private String ruleOperator;
	/**
	 * 额外条件.
	 */
    @Column(name = "RULE_CONDITION")
	private String ruleCondition;
	/**
	 * 是否启用.
	 */
    @Column(name = "STATUS")
	private String status;
	/**
	 * 备注.
	 */
    @Column(name = "REMARK")
	private String remark;
	/**
	 * 所属人id.
	 */
    @Column(name = "PARTY_ID")
	private String partyId;
	/**
	 * 所属人类型 user role 等.
	 */
    @Column(name = "PARTY_TYPE")
	private String partyType;
	
	// Constructors
 
    /** default constructor */
	public DrcAuthRule() {
	}

	/**
	 * .
	 * @return
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * .
	 * @param id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * 所属配置id预留 暂时不用.
	 * @return
	 */
	public Long getCfgId() {
		return this.cfgId;
	}

	/**
	 * 所属配置id预留 暂时不用.
	 * @param cfgId
	 */
	public void setCfgId(Long cfgId) {
		this.cfgId = cfgId;
	}

	/**
	 * 规则类型：org user 等 org时 登录时会切换单位信息.
	 * @return
	 */
	public String getRuleType() {
		return this.ruleType;
	}

	/**
	 * 规则类型：org user 等 org时 登录时会切换单位信息.
	 * @param ruleType
	 */
	public void setRuleType(String ruleType) {
		this.ruleType = ruleType;
	}

	/**
	 * 字段名称.
	 * @return
	 */
	public String getRuleField() {
		return this.ruleField;
	}

	/**
	 * 字段名称.
	 * @param ruleField
	 */
	public void setRuleField(String ruleField) {
		this.ruleField = ruleField;
	}

	/**
	 * 字段值.
	 * @return
	 */
	public String getRuleValue() {
		return this.ruleValue;
	}

	/**
	 * 字段值.
	 * @param ruleValue
	 */
	public void setRuleValue(String ruleValue) {
		this.ruleValue = ruleValue;
	}

	/**
	 * 操作类型：= <>  > < 等 为空 默认=.
	 * @return
	 */
	public String getRuleOperator() {
		return this.ruleOperator;
	}

	/**
	 * 操作类型：= <>  > < 等 为空 默认=.
	 * @param ruleOperator
	 */
	public void setRuleOperator(String ruleOperator) {
		this.ruleOperator = ruleOperator;
	}

	/**
	 * 额外条件.
	 * @return
	 */
	public String getRuleCondition() {
		return this.ruleCondition;
	}

	/**
	 * 额外条件.
	 * @param ruleCondition
	 */
	public void setRuleCondition(String ruleCondition) {
		this.ruleCondition = ruleCondition;
	}

	/**
	 * 是否启用.
	 * @return
	 */
	public String getStatus() {
		return this.status;
	}

	/**
	 * 是否启用.
	 * @param status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * 备注.
	 * @return
	 */
	public String getRemark() {
		return this.remark;
	}

	/**
	 * 备注.
	 * @param remark
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * 所属人id.
	 * @return
	 */
	public String getPartyId() {
		return this.partyId;
	}

	/**
	 * 所属人id.
	 * @param partyId
	 */
	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	/**
	 * 所属人类型 user role 等.
	 * @return
	 */
	public String getPartyType() {
		return this.partyType;
	}

	/**
	 * 所属人类型 user role 等.
	 * @param partyTye
	 */
	public void setPartyType(String partyType) {
		this.partyType = partyType;
	}

}