/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Fri Dec 02 09:05:47 CST 2016
 */
package com.bosssoft.egov.asset.attach.service;

import java.util.List;

import com.bosssoft.egov.asset.attach.entity.AssetAttachBiz;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;



/**
 * Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2016-12-02   xiedeshou　　　新建
 * </pre>
 */
public interface AssetAttachBizService {

/**
	 * 增加.
	 * 
	 * @param assetAttachBiz 
	 */
	public void addAssetAttachBiz(AssetAttachBiz assetAttachBiz);

	/**
	 * 删除及相关信息.
	 * 
	 * @param assetAttachBiz 
	 */
	public void delAssetAttachBiz(AssetAttachBiz assetAttachBiz);

	/**
	 * 修改.
	 * 
	 * @param assetAttachBiz 
	 */
	public void updateAssetAttachBiz(AssetAttachBiz assetAttachBiz);

	/**
	 * 获取列表.
	 * 
	 */
	public List<AssetAttachBiz> getAssetAttachBizList(AssetAttachBiz assetAttachBiz);




   	/**
	 * 获取分页.
	 * 
		 */
	public Page<AssetAttachBiz> queryAssetAttachBizPage(Searcher searcher, Page<AssetAttachBiz> page);
			
    
}
 