/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Fri Dec 02 09:05:47 CST 2016
 */
package com.bosssoft.egov.asset.attach.service;

import java.io.InputStream;
import java.util.List;
import java.util.Map;

import com.bosssoft.egov.asset.attach.entity.AssetAttachFile;
import com.bosssoft.egov.asset.attach.entity.AssetAttachItem;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;
import com.bosssoft.platform.runtime.spi.User;



/**
 * Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2016-12-02   xiedeshou　　　新建
 * </pre>
 */
public interface AssetAttachFileService {

     /**
	 * 增加.
	 * 
	 * @param assetAttachFile 
	 */
	public void addAssetAttachFile(AssetAttachFile assetAttachFile);
	
	public void saveAttachFile(AssetAttachFile assetAttachFile, InputStream is);
	/**
	 * 删除及相关信息.
	 * 
	 * @param assetAttachFile 
	 */
	public void delAssetAttachFile(AssetAttachFile assetAttachFile);

	public void delAttachFile(Object fileId,User user);
	/**
	 * 修改.
	 * 
	 * @param assetAttachFile 
	 */
	public void updateAssetAttachFile(AssetAttachFile assetAttachFile);

	/**
	 * 获取列表.
	 * 
	 */
	public List<AssetAttachFile> getAssetAttachFileList(AssetAttachFile assetAttachFile);

	public List<AssetAttachFile> queryAttachFileInfosByBizId(String bizId);

	public AssetAttachFile queryOneAttachFile(Object fileId);
	
	public InputStream downloadFile(Object fileId);
	
	/**
	 * 
	 * <p>函数名称：getAssetAttachItems        </p>
	 * <p>功能说明： 获取附件项信息列表
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param appId 应用id
	 * @param bizType 业务类型
	 * @return
	 *
	 * @date   创建时间：2016年12月19日
	 * @author 作者：xds
	 */
	public List<AssetAttachItem> getAssetAttachItems(String appId, String[] bizType, String[] itemType,String grade);
	public List<AssetAttachItem> getAssetAttachItems(String appId, String[] bizType, String[] itemType,String grade,String[] excludeItemCode,String[] includeItemType);

   	/**
	 * 获取分页.
	 * 
	 */
	public Page<AssetAttachFile> queryAssetAttachFilePage(Searcher searcher, Page<AssetAttachFile> page);
	
	public List<AssetAttachItem> checkAttachItems(String appId, String[] bizType, String[] itemType);
	
	/**
	 * 
	 * <p>函数名称：  checkAttachmentRequired      </p>
	 * <p>功能说明： 核验附件是否有必填项：有文件或者填写了文字说明
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param appId
	 * @param bizType
	 * @param itemType
	 * @param grade
	 * @param bizId
	 * @return 返回校验不通过的附件列表
	 *
	 * @date   创建时间：2017年8月13日
	 * @author 作者：xds
	 */
	public List<AssetAttachItem> checkAttachmentRequired(String appId, String[] bizType, String[] itemType,String grade, String bizId);
	/**
	 * 
	 * <p>函数名称：  checkAttachmentRequired      </p>
	 * <p>功能说明： 核验附件是否有必填项：有文件或者填写了文字说明
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param appId
	 * @param bizType
	 * @param itemType
	 * @param grade
	 * @param bizId
	 * @return 返回校验不通过的附件列表
	 *
	 * @date   创建时间：2017年8月13日
	 * @author 作者：xds
	 */
	public List<AssetAttachItem> checkAttachmentRequired(String appId, String[] bizType, String[] itemType,String grade, String[] excludeItemCode,String[] includeItemType,String bizId);
	
	/**
	 * 
	 * <p>函数名称：checkIncludeAtLeastOneAttachment        </p>
	 * <p>功能说明：验证附件是否至少包含一个文件切无文件的 填写了文字说明
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param appId
	 * @param bizType
	 * @param itemType
	 * @param grade
	 * @param bizId
	 * @return
	 *
	 * @date   创建时间：2017年8月13日
	 * @author 作者：xds
	 */
	public boolean checkIncludeAtLeastOneAttachment(String appId, String[] bizType, String[] itemType,String grade, String bizId); 
	/**
	 * 
	 * <p>函数名称：checkIncludeAtLeastOneAttachment        </p>
	 * <p>功能说明：验证附件是否至少包含几个个文件切无文件的 填写了文字说明
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param appId
	 * @param bizType
	 * @param itemType
	 * @param grade
	 * @param bizId
	 * @param atleastCnt 至少包含几个
	 * @return
	 *
	 * @date   创建时间：2017年8月13日
	 * @author 作者：xds
	 */
	public boolean checkIncludeAtLeastOneAttachment(String appId, String[] bizType, String[] itemType,String grade, String bizId,int atleastCnt); 
	public boolean checkIncludeAtLeastOneAttachment(String appId, String[] bizType, String[] itemType,String grade, String[] excludeItemCode,String[] includeItemType,String bizId,int atleastCnt); 
	
	/**
	 * 
	 * <p>函数名称：  updateAttachFileByBizId      </p>
	 * <p>功能说明： 逻辑删除附件
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param bizId
	 * @return
	 *
	 * @date   创建时间：2017年10月9日
	 * @author 作者：wujian
	 */
	public Map<String, String> updateAttachFileByBizId(String bizId);
}
 