/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Mon Sep 11 21:10:27 CST 2017
 */
package com.bosssoft.asset.etl.entity;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import com.bosssoft.egov.asset.basic.entity.Entity;

/**
 * 对象.通用导入导出  ASSET_ETL_CONFIG 配置主表
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-09-11   xiedeshou　　　新建
 * </pre>
 */
 @Table(name = "ASSET_ETL_CONFIG")
public class AssetEtlConfig extends Entity {

	private static final long serialVersionUID = 170911211051256L;
	
	// Fields
	
	/**
	 * .
	 */
	@Id
    @Column(name = "ID")
	private Long id;
	/**
	 * .配置编码
	 */
    @Column(name = "CONFIG_CODE")
	private String configCode;
	/**
	 * .配置名称
	 */
    @Column(name = "CONFIG_NAME")
	private String configName;
	/**
	 * .数据输入类型：TXT\DB\EXCEL等等
	 */
    @Column(name = "IN_TYPE")
	private String inType;
	/**
	 * .数据输出类型：TXT\DB\EXCEL等等
	 */
    @Column(name = "OUT_TYPE")
	private String outType;
    
    /**
     * 处理后的接口调用，需要实现接口AfterProcessService
     */
    @Column(name = "BEAN_NAME")
    private String beanName;
    
    /**
     * 不为空时，直接运行ktr文件,目录相对路径：FileRecv\KETTLE 下 如：PD\A.ktr 
     */
    @Column(name = "KTR")
    private String ktr;
    
    /**
     * 模版文件名，如导入excel时的模版，相对目录：resources\template 下 如：DEPT|dept_import.xlsx
     */
    @Column(name = "TEMPLETE")
    private String templete;
    
    /**
     * 下载模版时的别名，如部门信息
     */
    @Column(name = "TEMPLETE_NAME")
    private String templeteName;
    
    /**
     * 导入时文件后缀列表
     */
    @Column(name = "FILE_EXTS")
    private String fileExts;
    
    /**
     * 导入文件大小
     */
    @Column(name = "FILE_MAX_SIZE")
    private String fileMaxSize;
    
	/**
	 * .状态
	 */
    @Column(name = "STATUS")
	private String status;
	/**
	 * .备注
	 */
    @Column(name = "REMARK")
	private String remark;
	
	// Constructors
 
    /** default constructor */
	public AssetEtlConfig() {
	}

	/**
	 * .
	 * @return
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * .
	 * @param id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * .
	 * @return
	 */
	public String getConfigCode() {
		return this.configCode;
	}

	/**
	 * .配置编码
	 * @param configCode
	 */
	public void setConfigCode(String configCode) {
		this.configCode = configCode;
	}

	/**
	 * .
	 * @return
	 */
	public String getConfigName() {
		return this.configName;
	}

	/**
	 * .
	 * @param configName
	 */
	public void setConfigName(String configName) {
		this.configName = configName;
	}

	/**
	 * .
	 * @return
	 */
	public String getInType() {
		return this.inType;
	}

	/**
	 * .
	 * @param inType
	 */
	public void setInType(String inType) {
		this.inType = inType;
	}

	/**
	 * .
	 * @return
	 */
	public String getOutType() {
		return this.outType;
	}

	/**
	 * .
	 * @param outType
	 */
	public void setOutType(String outType) {
		this.outType = outType;
	}

	public String getBeanName() {
		return beanName;
	}

	public void setBeanName(String beanName) {
		this.beanName = beanName;
	}

	/**
	 * .
	 * @return
	 */
	public String getStatus() {
		return this.status;
	}

	/**
	 * .
	 * @param status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * .
	 * @return
	 */
	public String getRemark() {
		return this.remark;
	}

	/**
	 * .
	 * @param remark
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getKtr() {
		return ktr;
	}

	public void setKtr(String ktr) {
		this.ktr = ktr;
	}

	public String getTemplete() {
		return templete;
	}

	public String getTempleteName() {
		return templeteName;
	}

	public void setTemplete(String templete) {
		this.templete = templete;
	}

	public void setTempleteName(String templeteName) {
		this.templeteName = templeteName;
	}

	public String getFileExts() {
		return fileExts;
	}

	public String getFileMaxSize() {
		return fileMaxSize;
	}

	public void setFileExts(String fileExts) {
		this.fileExts = fileExts;
	}

	public void setFileMaxSize(String fileMaxSize) {
		this.fileMaxSize = fileMaxSize;
	}

}