/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Fri Jun 02 16:31:51 CST 2017
 */
package com.bosssoft.egov.asset.activiti.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.bosssoft.egov.asset.activiti.entity.ActivitiAlarmMonitor;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;
import com.bosssoft.platform.persistence.common.Mapper;
import com.bosssoft.platform.runtime.exception.BusinessException;

/**
 * 类说明: Mapper接口（ Mapper层） .
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-06-02   jinbiao　　　新建
 * </pre>
 */

public interface ActivitiAlarmMonitorMapper extends Mapper<ActivitiAlarmMonitor> {

	/**
	 * 
	 * 查询分页. `
	 * 
	 * @param searcher
	 *            查询条件
	 * @param pageable
	 *            分页信息
	 * @return ActivitiAlarmMonitorPage列表
	 * @throws BusinessException
	 *             自定义异常
	 *
	 */
	public Page<ActivitiAlarmMonitor> queryActivitiAlarmMonitorPage(@Param("searcher") Searcher searcher, @Param("page") Page<ActivitiAlarmMonitor> page);

	public void updateTimeCompleteByBusIdAndTaskdef(@Param("time") String time, @Param("busId") String busId, @Param("taskdef") String taskdef,@Param("complete")Long complete,@Param("pid")String pid);
	
	public void updateReceiveTimeCompleteByBusIdAndTaskdef(@Param("time") String time, @Param("busId") String busId, @Param("taskdef") String taskdef,@Param("complete")Long complete,@Param("pid")String pid);
	
	public void updateReceiveTimeCompleteByBusIdAndTaskdefNoPid(@Param("time") String time, @Param("busId") String busId, @Param("taskdef") String taskdef,@Param("complete")Long complete);
	
	public void updateReceiveTimeCreateTimeCompleteByBusIdAndTaskdef(@Param("receiveTime") String receiveTime, @Param("createTime") String createTime, @Param("busId") String busId,
			@Param("taskdef") String taskdef, @Param("complete") Long complete, @Param("pid") String pid,@Param("endTime") String endTime);
	public void updateReceiveTimeCreateTimeCompleteByBusIdAndTaskdefNoPid(@Param("receiveTime") String receiveTime, @Param("createTime") String createTime, @Param("busId") String busId,
			@Param("taskdef") String taskdef, @Param("complete") Long complete, @Param("endTime") String endTime);

	public void updateCompleteByBusId(@Param("complete") Long complete, @Param("busId") String busId,@Param("pid")String pid);
	
	public void updateCompleteByBusIdNoPid(@Param("complete") Long complete, @Param("busId") String busId);
	
	public void updateCompleteEndTimeByBusIdByIsComplete(@Param("complete") Long complete, @Param("busId") String busId,@Param("pid")String pid,@Param("completebefore") Long completebefore, @Param("endtime")String endtime);
	
	public void updateCompleteEndTimeByBusIdByIsCompleteNoPid(@Param("complete") Long complete, @Param("busId") String busId,@Param("completebefore") Long completebefore, @Param("endtime")String endtime);
	
	public void updateCompleteEndTimeByBusId(@Param("complete") Long complete, @Param("busId") String busId,@Param("pid")String pid,@Param("endtime")String endtime, @Param("nodename") String nodename, @Param("nodedesc") String nodedesc);
	
	public void updateCompleteEndTimeByBusIdNoPid(@Param("complete") Long complete, @Param("busId") String busId,@Param("endtime")String endtime, @Param("nodename") String nodename, @Param("nodedesc") String nodedesc);

	public void updateReutrn(@Param("busId") String busId, @Param("complete") Long complete, @Param("time") String time);
	//跨出监控区域
	public void deleteByBusId(@Param("busId") String busId,@Param("pid") String pid);
	
	public void deleteByBusIdNoPid(@Param("busId") String busId);
	//跨出监控区域
	public void deleteByBusIdAndTaskdef(@Param("busId") String busId, @Param("taskdef") String taskdef);

	public void updateTaskDefByBusId(@Param("busId") String busId, @Param("complete")Long complete,  @Param("taskdef")String taskdef,@Param("pid")String pid);
	
	public void updateTaskDefByBusIdNoPid(@Param("busId") String busId, @Param("complete")Long complete,  @Param("taskdef")String taskdef);
	
	public void updateCurrentTaskDefRoleCode(@Param("busId") String busId, @Param("complete")Long complete,  @Param("currenttaskdef")String currenttaskdef,@Param("authrolecode")String authrolecode);
	
	public void updateCurrentTaskDefRoleCodeTaskName(@Param("busId") String busId, @Param("taskName") String taskName, @Param("complete")Long complete,  @Param("currenttaskdef")String currenttaskdef,@Param("authrolecode")String authrolecode,@Param("pid")String pid);
	
	public void updateCurrentTaskDefRoleCodeTaskNameNoPid(@Param("busId") String busId, @Param("taskName") String taskName, @Param("complete")Long complete,  @Param("currenttaskdef")String currenttaskdef,@Param("authrolecode")String authrolecode);
	
	public void updateCurrentTaskDefRoleCodeReceiveTime(@Param("busId") String busId, @Param("complete") Long complete, @Param("currenttaskdef") String currenttaskdef,
			@Param("authrolecode") String authrolecode, @Param("receivetime") String receivetime, @Param("nodename") String nodename, @Param("nodedesc") String nodedesc,@Param("pid") String pid);
	
	public void updateCurrentTaskDefRoleCodeReceiveTimeNoPid(@Param("busId") String busId, @Param("complete") Long complete, @Param("currenttaskdef") String currenttaskdef,
			@Param("authrolecode") String authrolecode, @Param("receivetime") String receivetime, @Param("nodename") String nodename, @Param("nodedesc") String nodedesc);
	
	public void updateCurrentTaskDefRoleCodeReceiveTimeBack2Zone(@Param("busId") String busId, @Param("complete") Long complete, @Param("currenttaskdef") String currenttaskdef,
			@Param("authrolecode") String authrolecode, @Param("receivetime") String receivetime, @Param("nodename") String nodename, @Param("nodedesc") String nodedesc,@Param("pid") String pid);
	
	public void updateCurrentTaskDefRoleCodeReceiveTimeNoPidBack2Zone(@Param("busId") String busId, @Param("complete") Long complete, @Param("currenttaskdef") String currenttaskdef,
			@Param("authrolecode") String authrolecode, @Param("receivetime") String receivetime, @Param("nodename") String nodename, @Param("nodedesc") String nodedesc);
	
	public void updateCurrentTaskDefRoleCodeReceiveTimeMiddle(@Param("busId") String busId, @Param("complete") Long complete, @Param("currenttaskdef") String currenttaskdef,
			@Param("authrolecode") String authrolecode, @Param("receivetime") String receivetime, @Param("nodename") String nodename, @Param("nodedesc") String nodedesc,@Param("pid") String pid);
	
	public void updateCurrentTaskDefRoleCodeReceiveTimeMiddleNoPid(@Param("busId") String busId, @Param("complete") Long complete, @Param("currenttaskdef") String currenttaskdef,
			@Param("authrolecode") String authrolecode, @Param("receivetime") String receivetime, @Param("nodename") String nodename, @Param("nodedesc") String nodedesc);
	
	public List<ActivitiAlarmMonitor> hasRecord(@Param("busId") String busId, @Param("taskdef")String taskdef, @Param("pid")String pid);
	
	public List<ActivitiAlarmMonitor> hasRecordNoPid(@Param("busId") String busId, @Param("taskdef")String taskdef);
	
	public List<ActivitiAlarmMonitor> hasRecordNoComplete(@Param("busId") String busId, @Param("taskdef")String taskdef, @Param("pid")String pid,@Param("complete")Long complete );
	
	public List<ActivitiAlarmMonitor> hasRecordNoCompleteNoPid(@Param("busId") String busId, @Param("taskdef")String taskdef,@Param("complete")Long complete );

	public List<ActivitiAlarmMonitor> getMonitorsNoPid(@Param("busId")String busId,@Param("zone")String zone);
	
	public List<ActivitiAlarmMonitor> getMonitors(@Param("busId")String busId,@Param("zone")String zone, @Param("pid") String pid);
	
	public void updateTimeByBusIdComplete(@Param("time") String time, @Param("busId") String busId,@Param("complete")Long complete );
	
	public void beginAlarmProcedure();
	
	public void dynamicAlarmPro(Map<String, Object> alarmMap);

	public void updateCompleteByBusIdExceptNowZone(@Param("complete")Long complete, @Param("busId")String busId, @Param("pid")String pid, @Param("taskdef")String taskdef);
	
	public void updateCompleteByBusIdExceptNowZoneNoPid(@Param("complete")Long complete, @Param("busId")String busId, @Param("taskdef")String taskdef);
}