/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sat Jan 07 11:33:23 CST 2017
 */
package com.bosssoft.egov.asset.activiti.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bosssoft.egov.asset.activiti.entity.AssetBusHistory;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.persistence.common.Mapper;
import com.bosssoft.platform.common.lang.data.Searcher;
import com.bosssoft.platform.runtime.exception.BusinessException;

/**
 * 类说明:  Mapper接口（ Mapper层） .
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-07   jinbiao　　　新建
 * </pre>

 */

public interface AssetBusHistoryMapper extends Mapper<AssetBusHistory>{



/**
	 * 
	 * 查询分页.
	 *	`
	 * @param searcher 查询条件
	 * @param pageable 分页信息
	 * @return AssetBusHistoryPage列表
	 * @throws BusinessException 自定义异常
	 *
	 */
	public Page<AssetBusHistory> queryAssetBusHistoryPage(@Param("searcher")Searcher searcher,@Param("page")Page<AssetBusHistory> page);
			
	public int updatePIdByBusId(@Param("busId")String busId,@Param("pId")String pId,@Param("busType")String busType);

	public int deleteByBusIdAndPId(@Param("busId")String busId,@Param("pId")String pId);

	public int deleteByBusIdUserCode(@Param("busId")String busId, @Param("userCode")String userCode);
	
	public int deleteByBusIdUserCodeCurrentTask(@Param("busId")String busId, @Param("userCode")String userCode, @Param("currentTask")String currentTask);

	public AssetBusHistory queryOne(@Param("busId")String busId, @Param("userCode")String userCode);
	
	public AssetBusHistory queryOneHistory(@Param("busId")String busId, @Param("userCode")String userCode, @Param("currentTask")String currentTask);

	public List<AssetBusHistory> queryCheckList(@Param("busId")String busId, @Param("userCode")String userCode, @Param("handle")String handle);

	public List<AssetBusHistory> queryCheckListByBusinessId(@Param("busId")String busId);

	public List<AssetBusHistory> queryCheckListByBusinessIdUserCode(@Param("busId")String busId, @Param("userCode")String userCode);

	public int updatePIdByBusIdAndBusType(@Param("busId")String busId,@Param("pId")String pId,@Param("busType")String busType);

	public int updateBusTypeByBusIdAndPid(@Param("busId")String busId,@Param("pId")String pId,@Param("busType")String busType);
}