/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Tue Dec 26 11:28:35 CST 2017
 */
package com.bosssoft.egov.asset.lifecycle.mapper;

import org.apache.ibatis.annotations.Param;

import com.bosssoft.egov.asset.lifecycle.entity.AssetLifeLog;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;
import com.bosssoft.platform.persistence.common.Mapper;

/**
 * 类说明: Mapper接口（ Mapper层） .
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-12-26   Wiesel　　　新建
 * </pre>
 * 
 */

public interface AssetLifeLogMapper extends Mapper<AssetLifeLog> {

	/**
	 * 
	 * 查询分页. `
	 * 
	 * @param searcher
	 *            查询条件
	 * @param pageable
	 *            分页信息
	 * @return AssetLifeLogPage列表
	 * @throws BusinessException
	 *             自定义异常
	 *
	 */
	public Page<AssetLifeLog> queryAssetLifeLogPage(@Param("searcher") Searcher searcher,
			@Param("page") Page<AssetLifeLog> page);

	public int delAssetLifeLog(@Param("assetLifeLog") AssetLifeLog assetLifeLog);

}