
/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sat Jan 07 11:41:43 CST 2017
 */
package com.bosssoft.egov.asset.assettype.service;
import com.bosssoft.platform.common.lang.data.Page;
import java.util.List;
import com.bosssoft.platform.common.lang.data.Searcher;
import com.bosssoft.egov.asset.assettype.entity.AssetClassifyOften;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.bosssoft.egov.asset.assettype.service.AssetClassifyOftenService;
import com.bosssoft.egov.asset.assettype.mapper.AssetClassifyOftenMapper;


/**
 * 类说明: AssetClassifyOftenService接口实现类. 
 *
 * 类用途：
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-07   Administrator　　　新建
 * </pre>
 */
@Service
public class AssetClassifyOftenServiceImpl implements AssetClassifyOftenService {

	private static Logger logger = LoggerFactory.getLogger(AssetClassifyOftenServiceImpl.class);

	// TODO 添加需要的Mapper
	@Autowired
	private AssetClassifyOftenMapper assetClassifyOftenMapper;
	
	/**
	 *
	 * @param assetClassifyOften
	 */
	public void addAssetClassifyOften(AssetClassifyOften assetClassifyOften)  {
		assetClassifyOftenMapper.insert(assetClassifyOften);
	}

	/**
	 *
	 * @param assetClassifyOften
	 */
	public void delAssetClassifyOften(AssetClassifyOften assetClassifyOften)  {
		assetClassifyOftenMapper.deleteByPrimaryKey(assetClassifyOften);
	}

	/**
	 *
	 * @param assetClassifyOften
	 */
	public void updateAssetClassifyOften(AssetClassifyOften assetClassifyOften)  {
		assetClassifyOftenMapper.updateByPrimaryKey(assetClassifyOften);
	}

	/**
	 *
	 * @param assetClassifyOften
	 * @retrun
	 */
	public List<AssetClassifyOften> getAssetClassifyOftenList(AssetClassifyOften assetClassifyOften)  {
		return null;
	}

	/**
	 *
	 * @param searcher
	 * @param page
	 * @retrun
	 */
	public Page<AssetClassifyOften> queryAssetClassifyOftenPage(Searcher searcher, Page<AssetClassifyOften> page)  {
		return null;
	}


}