/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Thu Feb 23 16:01:57 CST 2017
 */
package com.bosssoft.egov.asset.monitor.service;

import java.util.List;

import com.bosssoft.egov.asset.monitor.entity.FabMonitorRecordUrlortype;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;

/**
 * Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-02-23   jinbiao　　　新建
 * </pre>
 */
public interface FabMonitorRecordUrlortypeService {

	/**
	 * 增加.
	 * 
	 * @param fabMonitorRecordUrlortype
	 */
	public void addFabMonitorRecordUrlortype(FabMonitorRecordUrlortype fabMonitorRecordUrlortype);

	/**
	 * 删除及相关信息.
	 * 
	 * @param fabMonitorRecordUrlortype
	 */
	public void delFabMonitorRecordUrlortype(FabMonitorRecordUrlortype fabMonitorRecordUrlortype);

	/**
	 * 修改.
	 * 
	 * @param fabMonitorRecordUrlortype
	 */
	public void updateFabMonitorRecordUrlortype(FabMonitorRecordUrlortype fabMonitorRecordUrlortype);

	/**
	 * 获取列表.
	 * 
	 */
	public List<FabMonitorRecordUrlortype> getFabMonitorRecordUrlortypeList(FabMonitorRecordUrlortype fabMonitorRecordUrlortype);

	/**
	 * 获取分页.
	 * 
	 */
	public Page<FabMonitorRecordUrlortype> queryFabMonitorRecordUrlortypePage(Searcher searcher, Page<FabMonitorRecordUrlortype> page);

	/**
	 * 获取分页.
	 * 
	 */
	public FabMonitorRecordUrlortype queryFabMonitorRecordUrlortypeByBusType(String busType);

	public List<FabMonitorRecordUrlortype> getFabMonitorRecordUrlortypeListAll();
}
