/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Mon Jan 16 11:24:16 CST 2017
 */
package com.bosssoft.egov.asset.monitor.service;

import java.util.List;

import com.bosssoft.egov.asset.monitor.entity.FabMonitorModel;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;



/**
 * 监控数据模型Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-16   Administrator　　　新建
 * </pre>
 */
public interface FabMonitorModelService {

/**
	 * 增加监控数据模型.
	 * 
	 * @param fabMonitorModel 监控数据模型
	 */
	public void addFabMonitorModel(FabMonitorModel fabMonitorModel);

	/**
	 * 删除监控数据模型及相关信息.
	 * 
	 * @param fabMonitorModel 监控数据模型
	 */
	public void delFabMonitorModel(FabMonitorModel fabMonitorModel);

	/**
	 * 修改监控数据模型.
	 * 
	 * @param fabMonitorModel 监控数据模型
	 */
	public void updateFabMonitorModel(FabMonitorModel fabMonitorModel);

	/**
	 * 获取监控数据模型列表.
	 * 
	 */
	public List<FabMonitorModel> getFabMonitorModelList(FabMonitorModel fabMonitorModel);




   	/**
	 * 获取监控数据模型分页.
	 * 
		 */
	public Page<FabMonitorModel> queryFabMonitorModelPage(Searcher searcher, Page<FabMonitorModel> page);

	public FabMonitorModel queryOne(String modelId);

	public void batchDelFabMonitorModel(List<FabMonitorModel> fabMonitorModels);
			
    
}
 