/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Mon Jan 16 11:24:16 CST 2017
 */
package com.bosssoft.egov.asset.monitor.service;

import java.util.List;

import com.bosssoft.egov.asset.monitor.entity.FabMonitorEvtVersion;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;



/**
 * 监控事项版本号表Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-16   Administrator　　　新建
 * </pre>
 */
public interface FabMonitorEvtVersionService {

/**
	 * 增加监控事项版本号表.
	 * 
	 * @param fabMonitorEvtVersion 监控事项版本号表
	 */
	public void addFabMonitorEvtVersion(FabMonitorEvtVersion fabMonitorEvtVersion);

	/**
	 * 删除监控事项版本号表及相关信息.
	 * 
	 * @param fabMonitorEvtVersion 监控事项版本号表
	 */
	public void delFabMonitorEvtVersion(FabMonitorEvtVersion fabMonitorEvtVersion);

	/**
	 * 修改监控事项版本号表.
	 * 
	 * @param fabMonitorEvtVersion 监控事项版本号表
	 */
	public void updateFabMonitorEvtVersion(FabMonitorEvtVersion fabMonitorEvtVersion);

	/**
	 * 获取监控事项版本号表列表.
	 * 
	 */
	public List<FabMonitorEvtVersion> getFabMonitorEvtVersionList(FabMonitorEvtVersion fabMonitorEvtVersion);




   	/**
	 * 获取监控事项版本号表分页.
	 * 
		 */
	public Page<FabMonitorEvtVersion> queryFabMonitorEvtVersionPage(Searcher searcher, Page<FabMonitorEvtVersion> page);

	public FabMonitorEvtVersion queryByEvtId(String evtId);
			
    
}
 