package com.bosssoft.egov.asset.dictionary.impl.entity;

/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Wed Nov 16 09:31:08 CST 2016
 */

import javax.persistence.Column;
import javax.persistence.Table;

/**
 * 对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2016-11-16   Administrator　　　新建
 * </pre>
 */
 @Table(name = "AIMS_DICT_FINANCES_RELATION")
public class AimsDictFinancesRelation implements java.io.Serializable {

	private static final long serialVersionUID = 161116093200472L;
	
	// Fields
	
	/**
	 * 所属财政关系ID.
	 */
    @Column(name = "FINANCES_RELATION_ID")
	private Long financesRelationId;
	/**
	 * 所属财政关系PID.
	 */
    @Column(name = "FINANCES_RELATION_PID")
	private Long financesRelationPid;
	/**
	 * 所属财政关系编码.
	 */
    @Column(name = "FINANCES_RELATION_CODE")
	private String financesRelationCode;
	/**
	 * 所属财政关系父编码.
	 */
    @Column(name = "FINANCES_RELATION_PCODE")
	private String financesRelationPcode;
	/**
	 * 所属财政关系名称.
	 */
    @Column(name = "FINANCES_RELATION_NAME")
	private String financesRelationName;
	/**
	 * 级数.
	 */
    @Column(name = "FINANCES_RELATION_RANK")
	private Integer financesRelationRank;
	/**
	 * 最细级.
	 */
    @Column(name = "FINANCES_RELATION_ISLEAF")
	private Integer financesRelationIsleaf;
	/**
	 * 状态.
	 */
    @Column(name = "FINANCES_RELATION_STATUS")
	private String financesRelationStatus;
	/**
	 * 创建者.
	 */
    @Column(name = "CREATOR")
	private String creator;
	/**
	 * 所属财政关系父类名称.
	 */
    @Column(name = "FINANCES_RELATION_PNAME")
	private String financesRelationPname;
	/**
	 * 创建时间.
	 */
    @Column(name = "CREATEDATE")
	private String createdate;
	
	// Constructors
 
    /** default constructor */
	public AimsDictFinancesRelation() {
	}

	/**
	 * 所属财政关系ID.
	 * @return
	 */
	public Long getFinancesRelationId() {
		return this.financesRelationId;
	}

	/**
	 * 所属财政关系ID.
	 * @param financesRelationId
	 */
	public void setFinancesRelationId(Long financesRelationId) {
		this.financesRelationId = financesRelationId;
	}

	/**
	 * 所属财政关系PID.
	 * @return
	 */
	public Long getFinancesRelationPid() {
		return this.financesRelationPid;
	}

	/**
	 * 所属财政关系PID.
	 * @param financesRelationPid
	 */
	public void setFinancesRelationPid(Long financesRelationPid) {
		this.financesRelationPid = financesRelationPid;
	}

	/**
	 * 所属财政关系编码.
	 * @return
	 */
	public String getFinancesRelationCode() {
		return this.financesRelationCode;
	}

	/**
	 * 所属财政关系编码.
	 * @param financesRelationCode
	 */
	public void setFinancesRelationCode(String financesRelationCode) {
		this.financesRelationCode = financesRelationCode;
	}

	/**
	 * 所属财政关系父编码.
	 * @return
	 */
	public String getFinancesRelationPcode() {
		return this.financesRelationPcode;
	}

	/**
	 * 所属财政关系父编码.
	 * @param financesRelationPcode
	 */
	public void setFinancesRelationPcode(String financesRelationPcode) {
		this.financesRelationPcode = financesRelationPcode;
	}

	/**
	 * 所属财政关系名称.
	 * @return
	 */
	public String getFinancesRelationName() {
		return this.financesRelationName;
	}

	/**
	 * 所属财政关系名称.
	 * @param financesRelationName
	 */
	public void setFinancesRelationName(String financesRelationName) {
		this.financesRelationName = financesRelationName;
	}

	/**
	 * 级数.
	 * @return
	 */
	public Integer getFinancesRelationRank() {
		return this.financesRelationRank;
	}

	/**
	 * 级数.
	 * @param financesRelationRank
	 */
	public void setFinancesRelationRank(Integer financesRelationRank) {
		this.financesRelationRank = financesRelationRank;
	}

	/**
	 * 最细级.
	 * @return
	 */
	public Integer getFinancesRelationIsleaf() {
		return this.financesRelationIsleaf;
	}

	/**
	 * 最细级.
	 * @param financesRelationIsleaf
	 */
	public void setFinancesRelationIsleaf(Integer financesRelationIsleaf) {
		this.financesRelationIsleaf = financesRelationIsleaf;
	}

	/**
	 * 状态.
	 * @return
	 */
	public String getFinancesRelationStatus() {
		return this.financesRelationStatus;
	}

	/**
	 * 状态.
	 * @param financesRelationStatus
	 */
	public void setFinancesRelationStatus(String financesRelationStatus) {
		this.financesRelationStatus = financesRelationStatus;
	}

	/**
	 * 创建者.
	 * @return
	 */
	public String getCreator() {
		return this.creator;
	}

	/**
	 * 创建者.
	 * @param creator
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * 所属财政关系父类名称.
	 * @return
	 */
	public String getFinancesRelationPname() {
		return this.financesRelationPname;
	}

	/**
	 * 所属财政关系父类名称.
	 * @param financesRelationPname
	 */
	public void setFinancesRelationPname(String financesRelationPname) {
		this.financesRelationPname = financesRelationPname;
	}

	/**
	 * 创建时间.
	 * @return
	 */
	public String getCreatedate() {
		return this.createdate;
	}

	/**
	 * 创建时间.
	 * @param createdate
	 */
	public void setCreatedate(String createdate) {
		this.createdate = createdate;
	}

}