/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sun Nov 20 15:30:24 CST 2016
 */
package com.bosssoft.egov.asset.assettype.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.bosssoft.egov.asset.assettype.entity.AssetDictClassify;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.persistence.common.Mapper;
import com.bosssoft.platform.common.lang.data.Searcher;
import com.bosssoft.platform.runtime.exception.BusinessException;

/**
 * 类说明:  Mapper接口（ Mapper层） .
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2016-11-20   xiedeshou　　　新建
 * </pre>

 */

public interface AssetDictClassifyMapper  extends Mapper<AssetDictClassify>{



/**
	 * 
	 * 查询分页.
	 *	`
	 * @param searcher 查询条件
	 * @param pageable 分页信息
	 * @return AssetDictAssetClassifyPage列表
	 * @throws BusinessException 自定义异常
	 *
	 */
	public Page<AssetDictClassify> queryAssetDictClassifyPage(@Param("searcher")Searcher searcher,@Param("page")Page<AssetDictClassify> page);
			

	public List<AssetDictClassify> queryAssetClassifyMapper(@Param("typeId")String typeId,@Param("table") String table);
	
	public List<AssetDictClassify> queryAssertClassifyBySql(@Param("tableName") String tableName,@Param("where") String where);
	public List<AssetDictClassify> queryAssertClassifyBySqlCondition(@Param("sql") String sql,@Param("params")Map<String,String> params);
}