/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sat Mar 04 11:38:06 CST 2017
 */
package com.bosssoft.egov.asset.activiti.service;

import java.util.List;

import com.bosssoft.egov.asset.activiti.entity.ActivitiBizAction;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;



/**
 * Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-03-04   jinbiao　　　新建
 * </pre>
 */
public interface ActivitiBizActionService {

/**
	 * 增加.
	 * 
	 * @param activitiBizAction 
	 */
	public void addActivitiBizAction(ActivitiBizAction activitiBizAction);

	/**
	 * 删除及相关信息.
	 * 
	 * @param activitiBizAction 
	 */
	public void delActivitiBizAction(ActivitiBizAction activitiBizAction);

	/**
	 * 修改.
	 * 
	 * @param activitiBizAction 
	 */
	public void updateActivitiBizAction(ActivitiBizAction activitiBizAction);

	/**
	 * 获取列表.
	 * 
	 */
	public List<ActivitiBizAction> getActivitiBizActionList(ActivitiBizAction activitiBizAction);




   	/**
	 * 获取分页.
	 * 
		 */
	public Page<ActivitiBizAction> queryActivitiBizActionPage(Searcher searcher, Page<ActivitiBizAction> page);
			
    
}
 