/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Tue Dec 27 14:32:22 CST 2016
 */
package com.bosssoft.egov.asset.activiti.service;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.List;

import javax.servlet.http.HttpServletResponse;
import javax.xml.stream.XMLStreamException;

import org.activiti.engine.repository.Model;

import com.bosssoft.egov.asset.activiti.entity.ActReModel;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;

/**
 * Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2016-12-27   jinbiao　　　新建
 * </pre>
 */
public interface ActReModelService {

	/**
	 * 增加.
	 * 
	 * @param actReModel
	 */
	public void addActReModel(ActReModel actReModel);

	/**
	 * 删除及相关信息.
	 * 
	 * @param actReModel
	 */
	public void delActReModel(ActReModel actReModel);

	/**
	 * 修改.
	 * 
	 * @param actReModel
	 */
	public void updateActReModel(ActReModel actReModel);

	/**
	 * 获取列表.
	 * 
	 */
	public List<ActReModel> getActReModelList(ActReModel actReModel);

	/**
	 * 获取分页.
	 * 
	 */
	public Page<ActReModel> queryActReModelPage(Searcher searcher, Page<ActReModel> page);

	public Model create(String name, String key, String description, String category) throws UnsupportedEncodingException;

	public String deploy(String id);

	public void export(String id, HttpServletResponse response);

	public void updateCategory(String id, String category);

	public void delete(String id);
	
	public void batchDelete(List<ActReModel> model);
	
	public Model convertToModel(String procDefId) throws UnsupportedEncodingException, XMLStreamException;
	
	public List<String> exportDiagrams(String exportDir) throws IOException;
}
