/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Wed Mar 01 15:12:59 CST 2017
 */
package com.bosssoft.egov.asset.activiti.service;

import java.util.List;

import com.bosssoft.egov.asset.activiti.entity.AssetActivitiConfig;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;



/**
 * Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-03-01   jinbiao　　　新建
 * </pre>
 */
public interface AssetActivitiConfigService {

/**
	 * 增加.
	 * 
	 * @param assetActivitiConfig 
	 */
	public void addAssetActivitiConfig(AssetActivitiConfig assetActivitiConfig);

	/**
	 * 删除及相关信息.
	 * 
	 * @param assetActivitiConfig 
	 */
	public void delAssetActivitiConfig(AssetActivitiConfig assetActivitiConfig);

	/**
	 * 修改.
	 * 
	 * @param assetActivitiConfig 
	 */
	public void updateAssetActivitiConfig(AssetActivitiConfig assetActivitiConfig);

	/**
	 * 获取列表.
	 * 
	 */
	public List<AssetActivitiConfig> getAssetActivitiConfigList(AssetActivitiConfig assetActivitiConfig);




   	/**
	 * 获取分页.
	 * 
		 */
	public Page<AssetActivitiConfig> queryAssetActivitiConfigPage(Searcher searcher, Page<AssetActivitiConfig> page);
			
    public AssetActivitiConfig getOneConfigByKeyAndUserTaskDef(AssetActivitiConfig config);
}
 