/*******************************************************************************
 * 福建博思软件1997-2017 版权所有
 * 
 * Auto generated by Bosssoft Studio version 1.0 beta
 * 2018年1月26日下午4:44:18
 *******************************************************************************/
package com.bosssoft.egov.asset.skin.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.bosssoft.egov.asset.skin.entiry.AssetSkinCfg;
import com.bosssoft.egov.asset.skin.service.AssetSkinCfgService;
import com.bosssoft.platform.runtime.web.response.AjaxResult;

/**
 * @ClassName	类名：AssetSkinCfgController.java
 * @Description	功能说明：用户皮肤设置controller
 * <pre>
 * @date		创建日期：2018年1月26日
 * @author		创建人：chenzhibin
 * @version		版本号：V1.0
 * <pre>
 *-------------------修订记录---------------------
 */
@Controller
@RequestMapping(value="asset/skin")
public class AssetSkinCfgController {

	@Autowired
	private AssetSkinCfgService skinCfgService;
	
	@ResponseBody
	@RequestMapping(value="getSkinCfg.do", name="获取当前用户皮肤配置")
	public AssetSkinCfg getSkinCfg(){
		return skinCfgService.getSkinCfg();
	}
	
	@ResponseBody
	@RequestMapping(value="addSkinCfg.do", name="添加或更新用户皮肤配置", method=RequestMethod.POST)
	public AjaxResult addSkinCfg(AssetSkinCfg skin){
		return skinCfgService.addSkinCfg(skin);
	}
}
