/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Wed Dec 07 08:28:12 CST 2016
 */
package com.bosssoft.egov.asset.codegen.entity;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2016-12-07   xiedeshou　　　新建
 * </pre>
 */
 @Table(name = "asset_codegen_rule")
public class AssetCodegenRule implements java.io.Serializable {

	private static final long serialVersionUID = 161207082824102L;
	
	// Fields
	
	/**
	 * .
	 */
	@Id	
    @Column(name = "ID")
	private Long id;
	/**
	 * .
	 */
    @Column(name = "CFG_ID")
	private Long cfgId;
	/**
	 * .
	 */
    @Column(name = "SXH")
	private Integer sxh;
	/**
	 * .
	 */
    @Column(name = "RULE_NAME")
	private String ruleName;
	/**
	 * .
	 */
    @Column(name = "RULE_VALUE")
	private String ruleValue;
	/**
	 * 填充方式
	 */
    @Column(name = "FILL_WAY")
	private String fillWay;
	/**
	 * 长度
	 */
    @Column(name = "LENGTH")
	private Integer length;
	/**
	 * .填充字符
	 */
    @Column(name = "FILL_CHAR")
	private String fillChar;
	/**
	 * .初始化值
	 */
    @Column(name = "INIT_VALUE")
	private String initValue;
	/**
	 * .状态
	 */
    @Column(name = "STATUS")
	private String status;
	/**
	 * .创建者id
	 */
    @Column(name = "CREATOR_ID")
	private String creatorId;
	/**
	 * .创建者
	 */
    @Column(name = "CREATOR")
	private String creator;
	/**
	 * .创建时间
	 */
    @Column(name = "CREATE_TIME")
	private String createTime;
	/**
	 * .备用字段
	 */
    @Column(name = "STR01")
	private String str01;
	/**
	 * .
	 */
    @Column(name = "STR02")
	private String str02;
	/**
	 * .
	 */
    @Column(name = "STR03")
	private String str03;
	/**
	 * .
	 */
    @Column(name = "STR04")
	private String str04;
	/**
	 * .
	 */
    @Column(name = "STR05")
	private String str05;
	/**
	 * .
	 */
    @Column(name = "REMARK")
	private String remark;
	
	// Constructors
 
    /** default constructor */
	public AssetCodegenRule() {
	}

	/**
	 * .
	 * @return
	 */	
	public Long getId() {
		return this.id;
	}

	/**
	 * .
	 * @param id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * .
	 * @return
	 */
	public Long getCfgId() {
		return this.cfgId;
	}

	/**
	 * .
	 * @param cfgId
	 */
	public void setCfgId(Long cfgId) {
		this.cfgId = cfgId;
	}

	/**
	 * .
	 * @return
	 */
	public Integer getSxh() {
		return this.sxh;
	}

	/**
	 * .
	 * @param sxh
	 */
	public void setSxh(Integer sxh) {
		this.sxh = sxh;
	}

	/**
	 * .
	 * @return
	 */
	public String getRuleName() {
		return this.ruleName;
	}

	/**
	 * .
	 * @param ruleName
	 */
	public void setRuleName(String ruleName) {
		this.ruleName = ruleName;
	}

	/**
	 * .
	 * @return
	 */
	public String getRuleValue() {
		return this.ruleValue;
	}

	/**
	 * .
	 * @param ruleValue
	 */
	public void setRuleValue(String ruleValue) {
		this.ruleValue = ruleValue;
	}

	/**
	 * .
	 * @return
	 */
	public String getFillWay() {
		return this.fillWay;
	}

	/**
	 * .
	 * @param fillWay
	 */
	public void setFillWay(String fillWay) {
		this.fillWay = fillWay;
	}

	/**
	 * .
	 * @return
	 */
	public Integer getLength() {
		return this.length == null ? 0 : this.length;
	}

	/**
	 * .
	 * @param length
	 */
	public void setLength(Integer length) {
		this.length = length;
	}

	/**
	 * .
	 * @return
	 */
	public String getFillChar() {
		return this.fillChar;
	}

	/**
	 * .
	 * @param fillChar
	 */
	public void setFillChar(String fillChar) {
		this.fillChar = fillChar;
	}

	/**
	 * .
	 * @return
	 */
	public String getInitValue() {
		return this.initValue;
	}

	/**
	 * .
	 * @param initValue
	 */
	public void setInitValue(String initValue) {
		this.initValue = initValue;
	}

	/**
	 * .
	 * @return
	 */
	public String getStatus() {
		return this.status;
	}

	/**
	 * .
	 * @param status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * .
	 * @return
	 */
	public String getCreatorId() {
		return this.creatorId;
	}

	/**
	 * .
	 * @param creatorId
	 */
	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	/**
	 * .
	 * @return
	 */
	public String getCreator() {
		return this.creator;
	}

	/**
	 * .
	 * @param creator
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * .
	 * @return
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * .
	 * @param createTime
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * .
	 * @return
	 */
	public String getStr01() {
		return this.str01;
	}

	/**
	 * .
	 * @param str01
	 */
	public void setStr01(String str01) {
		this.str01 = str01;
	}

	/**
	 * .
	 * @return
	 */
	public String getStr02() {
		return this.str02;
	}

	/**
	 * .
	 * @param str02
	 */
	public void setStr02(String str02) {
		this.str02 = str02;
	}

	/**
	 * .
	 * @return
	 */
	public String getStr03() {
		return this.str03;
	}

	/**
	 * .
	 * @param str03
	 */
	public void setStr03(String str03) {
		this.str03 = str03;
	}

	/**
	 * .
	 * @return
	 */
	public String getStr04() {
		return this.str04;
	}

	/**
	 * .
	 * @param str04
	 */
	public void setStr04(String str04) {
		this.str04 = str04;
	}

	/**
	 * .
	 * @return
	 */
	public String getStr05() {
		return this.str05;
	}

	/**
	 * .
	 * @param str05
	 */
	public void setStr05(String str05) {
		this.str05 = str05;
	}

	/**
	 * .
	 * @return
	 */
	public String getRemark() {
		return this.remark;
	}

	/**
	 * .
	 * @param remark
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

}