/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sat Jan 07 21:43:25 CST 2017
 */
package com.bosssoft.egov.asset.attach.entity;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 文件存储表对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-07   Administrator　　　新建
 * </pre>
 */
 @Table(name = "ASSET_ATTACH_FILESTORE")
public class AssetAttachFilestore implements java.io.Serializable {

	private static final long serialVersionUID = 170107214411080L;
	
	// Fields
	
	/**
	 * 主键.
	 */
	@Id
    @Column(name = "ID")
	private String id;
	/**
	 * 正文内容.
	 */
    @Column(name = "CONTENT")
	private byte[] content;
	
	// Constructors
 
    /** default constructor */
	public AssetAttachFilestore() {
	}

	/**
	 * 主键.
	 * @return
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * 主键.
	 * @param id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * 正文内容.
	 * @return
	 */
	public byte[] getContent() {
		return this.content;
	}

	/**
	 * 正文内容.
	 * @param content
	 */
	public void setContent(byte[] content) {
		this.content = content;
	}

}