/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Fri Jun 02 16:29:18 CST 2017
 */
package com.bosssoft.egov.asset.activiti.entity;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-06-02   jinbiao　　　新建
 * </pre>
 */
 @Table(name = "ACTIVITI_ALARM_MONITOR")
public class ActivitiAlarmMonitor implements java.io.Serializable {

	private static final long serialVersionUID = 170602163048550L;
	
	// Fields
	
	/**
	 * ID.
	 */
	@Id
    @Column(name = "ID")
	private Long id;
	/**
	 * 业务类型.
	 */
    @Column(name = "BUS_TYPE")
	private String busType;
	/**
	 * 业务ID.
	 */
    @Column(name = "BUS_ID")
	private String busId;
	/**
	 * 开始流程定义key.
	 */
    @Column(name = "TASKDEFKEYBEGIN")
	private String taskdefkeybegin;
    /**
     * 开始流程定义key.
     */
    @Column(name = "TASKDEFKEYEND")
    private String taskdefkeyend;
	/**
	 * 流程实例ID.
	 */
    @Column(name = "PID")
	private String pid;
	/**
	 * 当前区域是否完成.
	 */
    @Column(name = "IS_COMPLETE")
	private Long isComplete;

	/**
	 * 流程定义id版本信息.
	 */
    @Column(name = "PRODEF_ID")
	private String prodefId;
	/**
	 * 机构code.
	 */
    @Column(name = "ORG_CODE")
	private String orgCode;
	/**
	 * 创建时间.
	 */
    @Column(name = "CREATE_TIME")
	private String createTime;
	/**
	 * 流程描述.
	 */
    @Column(name = "PROCESS_DESC")
	private String processDesc;
    
    
    /**
     * 区域描述.
     */
    @Column(name = "ZONE")
    private String zone;
    
	/**
	 * 区域描述.
	 */
    @Column(name = "CURRENT_TASKDEF")
	private String currenttaskdef;

    /**
     * 区域描述.
     */
    @Column(name = "AUTH_ROLE_CODE")
    private String authrolecode;
    
    /**
     * 区域描述.
     */
    @Column(name = "RECEIVE_TIME")
    private String receivetime;
    
    /**
     * 区域描述.
     */
    @Column(name = "END_TIME")
    private String endtime;
    
    /**
     * 区域描述.
     */
    @Column(name = "TASK_NAME")
    private String taskname;
    
    /**
     * 区域描述.
     */
    @Column(name = "DESCRIPTION")
    private String description;
    
    /**
     * 当前区域是否进行预警监控
     */
    @Column(name = "IS_ALARM")
    private Long isalarm;
    
    /**
     * 表单类型.
     */
    @Column(name = "FORM_TYPE")
    private String formtype;
    
	// Constructors
 
    /** default constructor */
	public ActivitiAlarmMonitor() {
	}

	/**
	 * ID.
	 * @return
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * ID.
	 * @param id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * 业务类型.
	 * @return
	 */
	public String getBusType() {
		return this.busType;
	}

	/**
	 * 业务类型.
	 * @param busType
	 */
	public void setBusType(String busType) {
		this.busType = busType;
	}

	/**
	 * 业务ID.
	 * @return
	 */
	public String getBusId() {
		return this.busId;
	}

	/**
	 * 业务ID.
	 * @param busId
	 */
	public void setBusId(String busId) {
		this.busId = busId;
	}

	/**
	 * 流程实例ID.
	 * @return
	 */
	public String getPid() {
		return this.pid;
	}

	/**
	 * 流程实例ID.
	 * @param pid
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	/**
	 * 当前区域是否完成.
	 * @return
	 */
	public Long getIsComplete() {
		return this.isComplete;
	}

	/**
	 * 当前区域是否完成.
	 * @param isComplete
	 */
	public void setIsComplete(Long isComplete) {
		this.isComplete = isComplete;
	}

	/**
	 * 流程定义id版本信息.
	 * @return
	 */
	public String getProdefId() {
		return this.prodefId;
	}

	/**
	 * 流程定义id版本信息.
	 * @param prodefId
	 */
	public void setProdefId(String prodefId) {
		this.prodefId = prodefId;
	}

	/**
	 * 机构code.
	 * @return
	 */
	public String getOrgCode() {
		return this.orgCode;
	}

	/**
	 * 机构code.
	 * @param orgCode
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	/**
	 * 创建时间.
	 * @return
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * 创建时间.
	 * @param createTime
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * 流程描述.
	 * @return
	 */
	public String getProcessDesc() {
		return this.processDesc;
	}

	/**
	 * 流程描述.
	 * @param processDesc
	 */
	public void setProcessDesc(String processDesc) {
		this.processDesc = processDesc;
	}

	/**
	 * 区域描述.
	 * @return
	 */
	public String getZone() {
		return this.zone;
	}
	
	public void setZone(String zone) {
		this.zone = zone;
	}

	public String getTaskdefkeybegin() {
		return taskdefkeybegin;
	}

	public void setTaskdefkeybegin(String taskdefkeybegin) {
		this.taskdefkeybegin = taskdefkeybegin;
	}

	public String getTaskdefkeyend() {
		return taskdefkeyend;
	}

	public void setTaskdefkeyend(String taskdefkeyend) {
		this.taskdefkeyend = taskdefkeyend;
	}

	public String getCurrenttaskdef() {
		return currenttaskdef;
	}

	public void setCurrenttaskdef(String currenttaskdef) {
		this.currenttaskdef = currenttaskdef;
	}

	public String getAuthrolecode() {
		return authrolecode;
	}

	public void setAuthrolecode(String authrolecode) {
		this.authrolecode = authrolecode;
	}

	public String getReceivetime() {
		return receivetime;
	}

	public void setReceivetime(String receivetime) {
		this.receivetime = receivetime;
	}

	public String getEndtime() {
		return endtime;
	}

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	public String getTaskname() {
		return taskname;
	}

	public void setTaskname(String taskname) {
		this.taskname = taskname;
	}

	public Long getIsalarm() {
		return isalarm;
	}

	public void setIsalarm(Long isalarm) {
		this.isalarm = isalarm;
	}

	public String getFormtype() {
		return formtype;
	}

	public void setFormtype(String formtype) {
		this.formtype = formtype;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


	
}