/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Fri Jun 02 16:29:18 CST 2017
 */
package com.bosssoft.egov.asset.activiti.entity;

import org.activiti.engine.delegate.DelegateExecution;
import org.activiti.engine.delegate.DelegateTask;

/**
 * 对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-06-02   jinbiao　　　新建
 * </pre>
 */
public class ActivitiAlarmEvent implements java.io.Serializable {

	private static final long serialVersionUID = 170602163048550L;
	
	private DelegateTask task;
	
	private DelegateExecution execution;
	
	private String opType;
	
	private String zone;
	
	private String processDesc;
	
	private Long isAlarm;

	public DelegateTask getTask() {
		return task;
	}

	public void setTask(DelegateTask task) {
		this.task = task;
	}

	public DelegateExecution getExecution() {
		return execution;
	}

	public void setExecution(DelegateExecution execution) {
		this.execution = execution;
	}

	public String getOpType() {
		return opType;
	}

	public void setOpType(String opType) {
		this.opType = opType;
	}

	public String getZone() {
		return zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	public String getProcessDesc() {
		return processDesc;
	}

	public void setProcessDesc(String processDesc) {
		this.processDesc = processDesc;
	}

	public Long getIsAlarm() {
		return isAlarm;
	}

	public void setIsAlarm(Long isAlarm) {
		this.isAlarm = isAlarm;
	}
	
}