/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sat Mar 04 17:46:43 CST 2017
 */
package com.bosssoft.egov.asset.activiti.entity;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-03-04   jinbiao　　　新建
 * </pre>
 */
 @Table(name = "ACTIVITI_NEXT_USER")
public class ActivitiNextUser implements java.io.Serializable {

	private static final long serialVersionUID = 170304174654495L;
	
	// Fields
	
	/**
	 * ID.
	 */
	@Id
    @Column(name = "ID")
	private Long id;
	/**
	 * 业务ID.
	 */
    @Column(name = "BUS_ID")
	private String busId;
	/**
	 * usercode.
	 */
    @Column(name = "USER_CODE")
	private String userCode;
	/**
	 * userid.
	 */
    @Column(name = "USER_NAME")
	private String userName;
	/**
	 * 名称.
	 */
    @Column(name = "USER_ID")
	private String userId;
	/**
	 * 单位code.
	 */
    @Column(name = "ORG_CODE")
	private String orgCode;
	/**
	 * 当前任务ID，对应remark中的下一节点任务ID.
	 */
    @Column(name = "TASK_ID")
	private String taskId;
	/**
	 * 流程ID.
	 */
    @Column(name = "PROC_INST_ID")
	private String procInstId;
	/**
	 * 节点定义ID.
	 */
    @Column(name = "USER_TASK_ID")
	private String userTaskId;
	/**
	 * 任务名称.
	 */
    @Column(name = "TASK_NAME")
	private String taskName;
	/**
	 * 电话号码.
	 */
    @Column(name = "PHONE")
	private String phone;
	/**
	 * remark表中的ID记录.
	 */
    @Column(name = "REMARK_ID")
	private Long remarkId;
	/**
	 * 角色code.
	 */
    @Column(name = "ROLE_CODE")
	private String roleCode;
	/**
	 * 角色NAME.
	 */
    @Column(name = "ROLE_NAME")
	private String roleName;
	/**
	 * 业务类型.
	 */
    @Column(name = "BUS_TYPE")
	private String busType;
	/**
	 * 单位ID.
	 */
    @Column(name = "ORG_ID")
	private String orgId;
	/**
	 * 已读次数.
	 */
    @Column(name = "READ")
	private Long read;
	/**
	 * 办结状态 0 未办 1 已办 9 办结.
	 */
    @Column(name = "STATUS")
	private Integer status;
	/**
	 * 创建人id.
	 */
    @Column(name = "CREATOR_ID")
	private String creatorId;
	/**
	 * 创建人名称.
	 */
    @Column(name = "CREATOR")
	private String creator;
	/**
	 * 创建时间（原始单据创建时间）.
	 */
    @Column(name = "CREATE_TIME")
	private String createTime;
	/**
	 * 接收时间（这条记录创建时间）.
	 */
    @Column(name = "RECEIVE_TIME")
	private String receiveTime;
	/**
	 * 下一节点名称.
	 */
    @Column(name = "NEXT_TASK_NAME")
	private String nextTaskName;
	/**
	 * 区划.
	 */
    @Column(name = "RGN_ID")
	private String rgnId;
	/**
	 * .
	 */
    @Column(name = "RGN_CODE")
	private String rgnCode;
	/**
	 * .
	 */
    @Column(name = "RGN_NAME")
	private String rgnName;
	/**
	 * 单位.
	 */
    @Column(name = "ORG_NAME")
	private String orgName;
	/**
	 * 业务类型名称.
	 */
    @Column(name = "BUS_TYPE_NAME")
	private String busTypeName;
	/**
	 * 本人是否操作.
	 */
    @Column(name = "IS_TODO")
	private Integer isTodo;
	/**
	 * 是否发起方.
	 */
    @Column(name = "IS_REQUEST")
	private Long isRequest;
	
	// Constructors
 
    /** default constructor */
	public ActivitiNextUser() {
	}

	/**
	 * ID.
	 * @return
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * ID.
	 * @param id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * 业务ID.
	 * @return
	 */
	public String getBusId() {
		return this.busId;
	}

	/**
	 * 业务ID.
	 * @param busId
	 */
	public void setBusId(String busId) {
		this.busId = busId;
	}

	/**
	 * usercode.
	 * @return
	 */
	public String getUserCode() {
		return this.userCode;
	}

	/**
	 * usercode.
	 * @param userCode
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	/**
	 * userid.
	 * @return
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * userid.
	 * @param userName
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * 名称.
	 * @return
	 */
	public String getUserId() {
		return this.userId;
	}

	/**
	 * 名称.
	 * @param userId
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * 单位code.
	 * @return
	 */
	public String getOrgCode() {
		return this.orgCode;
	}

	/**
	 * 单位code.
	 * @param orgCode
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	/**
	 * 当前任务ID，对应remark中的下一节点任务ID.
	 * @return
	 */
	public String getTaskId() {
		return this.taskId;
	}

	/**
	 * 当前任务ID，对应remark中的下一节点任务ID.
	 * @param taskId
	 */
	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	/**
	 * 流程ID.
	 * @return
	 */
	public String getProcInstId() {
		return this.procInstId;
	}

	/**
	 * 流程ID.
	 * @param procInstId
	 */
	public void setProcInstId(String procInstId) {
		this.procInstId = procInstId;
	}

	/**
	 * 节点定义ID.
	 * @return
	 */
	public String getUserTaskId() {
		return this.userTaskId;
	}

	/**
	 * 节点定义ID.
	 * @param userTaskId
	 */
	public void setUserTaskId(String userTaskId) {
		this.userTaskId = userTaskId;
	}

	/**
	 * 任务名称.
	 * @return
	 */
	public String getTaskName() {
		return this.taskName;
	}

	/**
	 * 任务名称.
	 * @param taskName
	 */
	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	/**
	 * 电话号码.
	 * @return
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * 电话号码.
	 * @param phone
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * remark表中的ID记录.
	 * @return
	 */
	public Long getRemarkId() {
		return this.remarkId;
	}

	/**
	 * remark表中的ID记录.
	 * @param remarkId
	 */
	public void setRemarkId(Long remarkId) {
		this.remarkId = remarkId;
	}

	/**
	 * 角色code.
	 * @return
	 */
	public String getRoleCode() {
		return this.roleCode;
	}

	/**
	 * 角色code.
	 * @param roleCode
	 */
	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	/**
	 * 角色NAME.
	 * @return
	 */
	public String getRoleName() {
		return this.roleName;
	}

	/**
	 * 角色NAME.
	 * @param roleName
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * 业务类型.
	 * @return
	 */
	public String getBusType() {
		return this.busType;
	}

	/**
	 * 业务类型.
	 * @param busType
	 */
	public void setBusType(String busType) {
		this.busType = busType;
	}

	/**
	 * 单位ID.
	 * @return
	 */
	public String getOrgId() {
		return this.orgId;
	}

	/**
	 * 单位ID.
	 * @param orgId
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	/**
	 * 已读次数.
	 * @return
	 */
	public Long getRead() {
		return this.read;
	}

	/**
	 * 已读次数.
	 * @param read
	 */
	public void setRead(Long read) {
		this.read = read;
	}

	/**
	 * 办结状态 0 未办 1 已办 9 办结.
	 * @return
	 */
	public Integer getStatus() {
		return this.status;
	}

	/**
	 * 办结状态 0 未办 1 已办 9 办结.
	 * @param status
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * 创建人id.
	 * @return
	 */
	public String getCreatorId() {
		return this.creatorId;
	}

	/**
	 * 创建人id.
	 * @param creatorId
	 */
	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	/**
	 * 创建人名称.
	 * @return
	 */
	public String getCreator() {
		return this.creator;
	}

	/**
	 * 创建人名称.
	 * @param creator
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * 创建时间（原始单据创建时间）.
	 * @return
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * 创建时间（原始单据创建时间）.
	 * @param createTime
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * 接收时间（这条记录创建时间）.
	 * @return
	 */
	public String getReceiveTime() {
		return this.receiveTime;
	}

	/**
	 * 接收时间（这条记录创建时间）.
	 * @param receiveTime
	 */
	public void setReceiveTime(String receiveTime) {
		this.receiveTime = receiveTime;
	}

	/**
	 * 下一节点名称.
	 * @return
	 */
	public String getNextTaskName() {
		return this.nextTaskName;
	}

	/**
	 * 下一节点名称.
	 * @param nextTaskName
	 */
	public void setNextTaskName(String nextTaskName) {
		this.nextTaskName = nextTaskName;
	}

	/**
	 * 区划.
	 * @return
	 */
	public String getRgnId() {
		return this.rgnId;
	}

	/**
	 * 区划.
	 * @param rgnId
	 */
	public void setRgnId(String rgnId) {
		this.rgnId = rgnId;
	}

	/**
	 * .
	 * @return
	 */
	public String getRgnCode() {
		return this.rgnCode;
	}

	/**
	 * .
	 * @param rgnCode
	 */
	public void setRgnCode(String rgnCode) {
		this.rgnCode = rgnCode;
	}

	/**
	 * .
	 * @return
	 */
	public String getRgnName() {
		return this.rgnName;
	}

	/**
	 * .
	 * @param rgnName
	 */
	public void setRgnName(String rgnName) {
		this.rgnName = rgnName;
	}

	/**
	 * 单位.
	 * @return
	 */
	public String getOrgName() {
		return this.orgName;
	}

	/**
	 * 单位.
	 * @param orgName
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	/**
	 * 业务类型名称.
	 * @return
	 */
	public String getBusTypeName() {
		return this.busTypeName;
	}

	/**
	 * 业务类型名称.
	 * @param busTypeName
	 */
	public void setBusTypeName(String busTypeName) {
		this.busTypeName = busTypeName;
	}

	/**
	 * 本人是否操作.
	 * @return
	 */
	public Integer getIsTodo() {
		return this.isTodo;
	}

	/**
	 * 本人是否操作.
	 * @param isTodo
	 */
	public void setIsTodo(Integer isTodo) {
		this.isTodo = isTodo;
	}

	/**
	 * 是否发起方.
	 * @return
	 */
	public Long getIsRequest() {
		return this.isRequest;
	}

	/**
	 * 是否发起方.
	 * @param isRequest
	 */
	public void setIsRequest(Long isRequest) {
		this.isRequest = isRequest;
	}

}