/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Tue Dec 27 14:32:22 CST 2016
 */
package com.bosssoft.egov.asset.activiti.entity;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2016-12-27   jinbiao　　　新建
 * </pre>
 */
 @Table(name = "ACT_RE_MODEL")
public class ActReModel implements java.io.Serializable {

	private static final long serialVersionUID = 161227143957993L;
	
	// Fields
	
	/**
	 * .
	 */
	@Id
    @Column(name = "ID_")
	private Object id;
	/**
	 * .
	 */
    @Column(name = "REV_")
	private Long rev;
	/**
	 * .
	 */
    @Column(name = "NAME_")
	private Object name;
	/**
	 * .
	 */
    @Column(name = "KEY_")
	private Object key;
	/**
	 * .
	 */
    @Column(name = "CATEGORY_")
	private Object category;
	/**
	 * .
	 */
    @Column(name = "CREATE_TIME_")
	private String createTime;
	/**
	 * .
	 */
    @Column(name = "LAST_UPDATE_TIME_")
	private String lastUpdateTime;
	/**
	 * .
	 */
    @Column(name = "VERSION_")
	private Long version;
	/**
	 * .
	 */
    @Column(name = "META_INFO_")
	private Object metaInfo;
	
	// Constructors
 
    /** default constructor */
	public ActReModel() {
	}

	/**
	 * .
	 * @return
	 */
	public Object getId() {
		return this.id;
	}

	/**
	 * .
	 * @param id
	 */
	public void setId(Object id) {
		this.id = id;
	}

	/**
	 * .
	 * @return
	 */
	public Long getRev() {
		return this.rev;
	}

	/**
	 * .
	 * @param rev
	 */
	public void setRev(Long rev) {
		this.rev = rev;
	}

	/**
	 * .
	 * @return
	 */
	public Object getName() {
		return this.name;
	}

	/**
	 * .
	 * @param name
	 */
	public void setName(Object name) {
		this.name = name;
	}

	/**
	 * .
	 * @return
	 */
	public Object getKey() {
		return this.key;
	}

	/**
	 * .
	 * @param key
	 */
	public void setKey(Object key) {
		this.key = key;
	}

	/**
	 * .
	 * @return
	 */
	public Object getCategory() {
		return this.category;
	}

	/**
	 * .
	 * @param category
	 */
	public void setCategory(Object category) {
		this.category = category;
	}

	/**
	 * .
	 * @return
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") 
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * .
	 * @param createTime
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") 
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * .
	 * @return
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") 
	public String getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	/**
	 * .
	 * @param lastUpdateTime
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") 
	public void setLastUpdateTime(String lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * .
	 * @return
	 */
	public Long getVersion() {
		return this.version;
	}

	/**
	 * .
	 * @param version
	 */
	public void setVersion(Long version) {
		this.version = version;
	}

	/**
	 * .
	 * @return
	 */
	public Object getMetaInfo() {
		return this.metaInfo;
	}

	/**
	 * .
	 * @param metaInfo
	 */
	public void setMetaInfo(Object metaInfo) {
		this.metaInfo = metaInfo;
	}

}