/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sat Jan 07 11:31:09 CST 2017
 */
package com.bosssoft.egov.asset.activiti.entity;
import javax.persistence.Column;
import javax.persistence.Table;

import com.bosssoft.egov.asset.activiti.ActivitiIdGen;

/**
 * 对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-07   jinbiao　　　新建
 * </pre>
 */
 @Table(name = "ASSET_BUS_HISTORY")
public class AssetBusHistory implements java.io.Serializable {

	private static final long serialVersionUID = 170107113203936L;
	
	// Fields
	
	/**
	 * .
	 */
    @Column(name = "ID")
	private Long id;
	/**
	 * .
	 */
    @Column(name = "BUS_ID")
	private String busId;
	/**
	 * .
	 */
    @Column(name = "OPERATOR_ID")
	private String operatorId;
	/**
	 * .
	 */
    @Column(name = "CHECK_RESULT")
	private Integer checkResult;
    /**
     * .
     */
    @Column(name = "PROC_INST_ID")
    private String procInstId;
    /**
     * .
     */
    @Column(name = "OPERATE_DATE")
    private String operateDate;
    
    @Column(name = "BIZ_TYPE")
    private String bizType;
    
    
    @Column(name = "BEFORE_CHECK")
    private Integer beforeCheck;
    
    
    @Column(name = "CURRENT_TASK")
    private String currentTask;
    
    
    @Column(name = "BEFORE_TASK")
    private String beforeTask;
    
    @Column(name = "TASK_STATUS")
    private Integer taskStatus;
    
    @Column(name = "BEFORE_STATUS")
    private Integer beforeStatus;
	
	// Constructors
 
    /** default constructor */
	public AssetBusHistory() {
		this.id = ActivitiIdGen.newWKID();
	}

	/**
	 * .
	 * @return
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * .
	 * @param id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * .
	 * @return
	 */
	public String getBusId() {
		return this.busId;
	}

	/**
	 * .
	 * @param busId
	 */
	public void setBusId(String busId) {
		this.busId = busId;
	}

	/**
	 * .
	 * @return
	 */
	public String getOperatorId() {
		return this.operatorId;
	}

	/**
	 * .
	 * @param operatorId
	 */
	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * .
	 * @return
	 */
	public Integer getCheckResult() {
		return this.checkResult;
	}

	/**
	 * .
	 * @param checkResult
	 */
	public void setCheckResult(Integer checkResult) {
		this.checkResult = checkResult;
	}

	public String getProcInstId() {
		return procInstId;
	}

	public void setProcInstId(String procInstId) {
		this.procInstId = procInstId;
	}

	public String getOperateDate() {
		return operateDate;
	}

	public void setOperateDate(String operateDate) {
		this.operateDate = operateDate;
	}

	public String getBizType() {
		return bizType;
	}

	public void setBizType(String bizType) {
		this.bizType = bizType;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bizType == null) ? 0 : bizType.hashCode());
		result = prime * result + ((busId == null) ? 0 : busId.hashCode());
		result = prime * result + ((checkResult == null) ? 0 : checkResult.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((operateDate == null) ? 0 : operateDate.hashCode());
		result = prime * result + ((operatorId == null) ? 0 : operatorId.hashCode());
		result = prime * result + ((procInstId == null) ? 0 : procInstId.hashCode());
		return result;
	}

	public Integer getBeforeCheck() {
		return beforeCheck;
	}

	public void setBeforCheck(Integer beforeCheck) {
		this.beforeCheck = beforeCheck;
	}

	public String getCurrentTask() {
		return currentTask;
	}

	public void setCurrentTask(String currentTask) {
		this.currentTask = currentTask;
	}

	public String getBeforeTask() {
		return beforeTask;
	}

	public void setBeforeTask(String beforeTask) {
		this.beforeTask = beforeTask;
	}

	public Integer getTaskStatus() {
		return taskStatus;
	}

	public void setTaskStatus(Integer taskStatus) {
		this.taskStatus = taskStatus;
	}

	public Integer getBeforeStatus() {
		return beforeStatus;
	}

	public void setBeforeStatus(Integer beforeStatus) {
		this.beforeStatus = beforeStatus;
	}
	

}