/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Wed Mar 01 15:10:07 CST 2017
 */
package com.bosssoft.egov.asset.activiti.entity;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-03-01   jinbiao　　　新建
 * </pre>
 */
 @Table(name = "ASSET_ACTIVITI_CONFIG")
public class AssetActivitiConfig implements java.io.Serializable {

	private static final long serialVersionUID = 170301151022313L;
	
	// Fields
	
	/**
	 * ID.
	 */
	@Id
    @Column(name = "ID")
	private String id;
	/**
	 * 流程定义key.
	 */
    @Column(name = "PRODEFKEY")
	private String prodefkey;
	/**
	 * 任务节点ID.
	 */
    @Column(name = "USERTASKDEF")
	private String usertaskdef;
	/**
	 * 任务节点名称.
	 */
    @Column(name = "USERTASKNAME")
	private String usertaskname;
	/**
	 * 流程名称.
	 */
    @Column(name = "PROCESSNAME")
	private String processname;
	/**
	 * 权限表ID.
	 */
    @Column(name = "GROUP_ID")
	private String groupId;
	
	// Constructors
 
    /** default constructor */
	public AssetActivitiConfig() {
	}

	/**
	 * ID.
	 * @return
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * ID.
	 * @param id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * 流程定义key.
	 * @return
	 */
	public String getProdefkey() {
		return this.prodefkey;
	}

	/**
	 * 流程定义key.
	 * @param prodefkey
	 */
	public void setProdefkey(String prodefkey) {
		this.prodefkey = prodefkey;
	}

	/**
	 * 任务节点ID.
	 * @return
	 */
	public String getUsertaskdef() {
		return this.usertaskdef;
	}

	/**
	 * 任务节点ID.
	 * @param usertaskdef
	 */
	public void setUsertaskdef(String usertaskdef) {
		this.usertaskdef = usertaskdef;
	}

	/**
	 * 任务节点名称.
	 * @return
	 */
	public String getUsertaskname() {
		return this.usertaskname;
	}

	/**
	 * 任务节点名称.
	 * @param usertaskname
	 */
	public void setUsertaskname(String usertaskname) {
		this.usertaskname = usertaskname;
	}

	/**
	 * 流程名称.
	 * @return
	 */
	public String getProcessname() {
		return this.processname;
	}

	/**
	 * 流程名称.
	 * @param processname
	 */
	public void setProcessname(String processname) {
		this.processname = processname;
	}

	public String getGroupId() {
		return groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}
	

}