/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sat Sep 23 11:34:49 CST 2017
 */
package com.bosssoft.asset.etl.service;

import java.util.List;

import com.bosssoft.asset.etl.entity.AssetEtlConfigAttr;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;



/**
 * Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-09-23   xiedeshou　　　新建
 * </pre>
 */
public interface AssetEtlConfigAttrService {

/**
	 * 增加.
	 * 
	 * @param assetEtlConfigAttr 
	 */
	public void addAssetEtlConfigAttr(AssetEtlConfigAttr assetEtlConfigAttr);

	/**
	 * 删除及相关信息.
	 * 
	 * @param assetEtlConfigAttr 
	 */
	public void delAssetEtlConfigAttr(AssetEtlConfigAttr assetEtlConfigAttr);

	/**
	 * 修改.
	 * 
	 * @param assetEtlConfigAttr 
	 */
	public void updateAssetEtlConfigAttr(AssetEtlConfigAttr assetEtlConfigAttr);

	/**
	 * 获取列表.
	 * 
	 */
	public List<AssetEtlConfigAttr> getAssetEtlConfigAttrList(AssetEtlConfigAttr assetEtlConfigAttr);




   	/**
	 * 获取分页.
	 * 
		 */
	public Page<AssetEtlConfigAttr> queryAssetEtlConfigAttrPage(Searcher searcher, Page<AssetEtlConfigAttr> page);
			
    
}
 