/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Mon Sep 11 21:07:04 CST 2017
 */
package com.bosssoft.asset.etl.comp.service;

import java.util.List;

import com.bosssoft.asset.etl.comp.entity.AssetEtlCompConfig;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;



/**
 * 通用导入导出_源配置:如 excel 相关配置 txt 相关配置 单独创建一个表Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-09-11   xiedeshou　　　新建
 * </pre>
 */
public interface AssetEtlCompConfigService {

/**
	 * 增加通用导入导出_源配置:如 excel 相关配置 txt 相关配置 单独创建一个表.
	 * 
	 * @param assetEtlCompConfig 通用导入导出_源配置:如 excel 相关配置 txt 相关配置 单独创建一个表
	 */
	public void addAssetEtlCompConfig(AssetEtlCompConfig assetEtlCompConfig);

	/**
	 * 删除通用导入导出_源配置:如 excel 相关配置 txt 相关配置 单独创建一个表及相关信息.
	 * 
	 * @param assetEtlCompConfig 通用导入导出_源配置:如 excel 相关配置 txt 相关配置 单独创建一个表
	 */
	public void delAssetEtlCompConfig(AssetEtlCompConfig assetEtlCompConfig);

	/**
	 * 修改通用导入导出_源配置:如 excel 相关配置 txt 相关配置 单独创建一个表.
	 * 
	 * @param assetEtlCompConfig 通用导入导出_源配置:如 excel 相关配置 txt 相关配置 单独创建一个表
	 */
	public void updateAssetEtlCompConfig(AssetEtlCompConfig assetEtlCompConfig);

	/**
	 * 获取通用导入导出_源配置:如 excel 相关配置 txt 相关配置 单独创建一个表列表.
	 * 
	 */
	public List<AssetEtlCompConfig> getAssetEtlCompConfigList(AssetEtlCompConfig assetEtlCompConfig);




   	/**
	 * 获取通用导入导出_源配置:如 excel 相关配置 txt 相关配置 单独创建一个表分页.
	 * 
		 */
	public Page<AssetEtlCompConfig> queryAssetEtlCompConfigPage(Searcher searcher, Page<AssetEtlCompConfig> page);
			
    
}
 