package com.bosssoft.egov.asset.activiti.service.impl;


/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Wed Nov 30 13:42:01 CST 2016
 */

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.bosssoft.egov.asset.activiti.ActivitiIdGen;
import com.bosssoft.egov.asset.activiti.entity.AssetActivitiBus;
import com.bosssoft.egov.asset.activiti.mapper.AssetActivitiBusMapper;
import com.bosssoft.egov.asset.activiti.service.AssetActivitiBusService;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;


/**
 * 类说明: AssetActivitiBusService接口实现类. 
 *
 * 类用途：
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2016-11-30   jinbiao　　　新建
 * </pre>
 */
@Service
public class AssetActivitiBusServiceImpl implements AssetActivitiBusService {

	private static Logger logger = LoggerFactory.getLogger(AssetActivitiBusServiceImpl.class);

	// TODO 添加需要的Mapper
	@Autowired
	private AssetActivitiBusMapper assetActivitiBusMapper;
	
	/**
	 *
	 * @param assetActivitiBus
	 */
	public void addAssetActivitiBus(AssetActivitiBus assetActivitiBus)  {
		assetActivitiBus.setId(ActivitiIdGen.newWKID());
		assetActivitiBusMapper.insert(assetActivitiBus);
	}

	/**
	 *
	 * @param assetActivitiBus
	 */
	public void delAssetActivitiBus(AssetActivitiBus assetActivitiBus)  {
		assetActivitiBusMapper.deleteByPrimaryKey(assetActivitiBus);
	}

	/**
	 *
	 * @param assetActivitiBus
	 */
	public void updateAssetActivitiBus(AssetActivitiBus assetActivitiBus)  {
		assetActivitiBusMapper.updateByPrimaryKey(assetActivitiBus);
	}

	/**
	 *
	 * @param assetActivitiBus
	 * @retrun
	 */
	public List<AssetActivitiBus> getAssetActivitiBusList(AssetActivitiBus assetActivitiBus)  {
		return null;
	}

	/**
	 *
	 * @param searcher
	 * @param page
	 * @retrun
	 */
	public Page<AssetActivitiBus> queryAssetActivitiBusPage(Searcher searcher, Page<AssetActivitiBus> page)  {
		return assetActivitiBusMapper.queryAssetActivitiBusPage(searcher, page);
	}
	
	/**
	 *
	 * @param searcher
	 * @param page
	 * @retrun
	 */
	public AssetActivitiBus queryAssetActivitiBus(String busType)  {
		return assetActivitiBusMapper.queryAssetActivitiBus(busType);
	}
	public AssetActivitiBus queryAssetActivitiBusByKey(String key)  {
		return assetActivitiBusMapper.queryAssetActivitiBusByKey(key);
	}

	public List<AssetActivitiBus> getAssetActivitiBusList()  {
		return assetActivitiBusMapper.queryAll();
	}

}