/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Fri Oct 14 15:44:39 CST 2016
 */
package com.bosssoft.egov.asset.aims.api.org.service;

import java.util.List;
import java.util.Map;

import com.bosssoft.egov.asset.aims.api.config.entity.AssetSysConfig;
import com.bosssoft.egov.asset.aims.api.org.entity.AimsBasicOrg;
import com.bosssoft.egov.asset.aims.api.org.entity.AimsRegion;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;



/**
 * Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2016-10-14   huangzhenxiong　　　新建
 * </pre>
 */
public interface AimsBasicOrgService {

	/**
	 * <p>函数名称：addAimsBasicOrg        </p>
	 * <p>功能说明：新增单位信息
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param aimsBasicOrg 单位信息对象
	 * @return
	 *
	 * @date   创建时间：2016年11月29日
	 * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
	 */
	public Map<String, Object> addAimsBasicOrg(AimsBasicOrg aimsBasicOrg);

	
	/**
	 * <p>函数名称：delAimsBasicOrg        </p>
	 * <p>功能说明：删除单位信息
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param aimsBasicOrg 单位信息对象
	 * @return
	 *
	 * @date   创建时间：2016年11月29日
	 * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
	 */
	public Map<String, Object> delAimsBasicOrg(AimsBasicOrg aimsBasicOrg);

	
	/**
	 * <p>函数名称：updateAimsBasicOrg        </p>
	 * <p>功能说明：修改单位信息
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param aimsBasicOrg 单位信息对象
	 * @return
	 *
	 * @date   创建时间：2016年11月29日
	 * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
	 */
	public Map<String, Object> updateAimsBasicOrg(AimsBasicOrg aimsBasicOrg);

	/**
	 * 获取列表.
	 * 
	 */
	public List<AimsBasicOrg> getAimsBasicOrgList(AimsBasicOrg aimsBasicOrg);

   	/**
	 * 获取分页.
	 * 
		 */
	public Page<AimsBasicOrg> queryAimsBasicOrgPage(Searcher searcher, Page<?> pageInfo);
			

	/**
	 * <p>函数名称：queryOrgPageByOrgId        </p>
	 * <p>功能说明：根据单位ID重新分页
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param orgId     单位ID
	 * @param pageInfo  分页信息
	 * @return
	 *
	 * @date   创建时间：2016年10月24日
	 * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
	 */
	public Page<AimsBasicOrg> queryOrgPageByOrgId(Long orgId, Page<?> pageInfo);
    
	/**
     * <p>函数名称：doBatchDelete        </p>
     * <p>功能说明：批量删除单位信息
     *
     * </p>
     *<p>参数说明：</p>
     * @param aimsBasicOrgs 单位List集合
     * @return
     *
     * @date   创建时间：2016年10月18日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
     */
    public Map<String, Object> doBatchDelete(List<AimsBasicOrg> aimsBasicOrgs);
    
    /**
     * <p>函数名称：loadOrgTreeByOrgId        </p>
     * <p>功能说明：根据单位ID获取单位树
     *
     * </p>
     *<p>参数说明：</p>
     * @param orgId 单位ID 
     * @return
     *
     * @date   创建时间：2016年10月18日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
     */
    public List<AimsBasicOrg> loadOrgTreeByOrgPid(Long orgId);
    
    /**
     * <p>函数名称：queryMaxOrgCode        </p>
     * <p>功能说明：查询同级中最大的单位编码并加1
     *
     * </p>
     *<p>参数说明：</p>
     * @param aimsBasicOrg  单位信息对象
     * @return
     *
     * @date   创建时间：2016年10月19日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
     */
    public Map<String, Object> queryMaxOrgCode(AimsBasicOrg aimsBasicOrg);
    
    /**
     * <p>函数名称：queryMaxSubOrgCode        </p>
     * <p>功能说明：查询子级中最大的单位编码并加1
     *
     * </p>
     *<p>参数说明：</p>
     * @param aimsBasicOrg 单位信息对象
     * @return
     *
     * @date   创建时间：2016年10月19日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
     */
    public Map<String, Object> queryMaxSubOrgCode(AimsBasicOrg aimsBasicOrg);
    
    /**
     * <p>函数名称：queryOneByCode        </p>
     * <p>功能说明：根据单位编码查询单位信息
     *
     * </p>
     *<p>参数说明：</p>
     * @param orgCode  单位编码
     * @return
     *
     * @date   创建时间：2016年10月21日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
     */
    public AimsBasicOrg queryOneByCode(String orgCode);
    
    /**
     * <p>函数名称：queryOneById        </p>
     * <p>功能说明：根据单位ID查询单位信息
     *
     * </p>
     *<p>参数说明：</p>
     * @param orgId 预算单位ID
     * @return
     *
     * @date   创建时间：2016年11月22日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public AimsBasicOrg queryOneById(Long orgId);
    /**
     * <p>函数名称： doSplit       </p>
     * <p>功能说明：单位拆细
     *
     * </p>
     *<p>参数说明：</p>
     * @param aimsBasicOrg  单位信息对象
     * @return
     *
     * @date   创建时间：2016年11月18日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public Map<String, Object> doSplit(AimsBasicOrg aimsBasicOrg);
    
    
    /**
     * <p>函数名称：checkMove        </p>
     * <p>功能说明：校验是否可以移动单位
     *
     * </p>
     *<p>参数说明：</p>
     * @param aimsBasicOrg 单位信息
     * @return
     *
     * @date   创建时间：2016年12月20日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public Map<String, Object> checkMove(AimsBasicOrg aimsBasicOrg);
    /**
     * <p>函数名称：doMove        </p>
     * <p>功能说明：对单位进行移动
     *
     * </p>
     *<p>参数说明：</p>
     * @param aimsBasicOrg  单位信息对象
     * @return
     *
     * @date   创建时间：2016年11月22日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public Map<String, Object> doMove(AimsBasicOrg aimsBasicOrg);

    /**
     * <p>函数名称：doEnable        </p>
     * <p>功能说明：根据单位ID 设置单位(单位)的使用状态为启用
     *
     * </p>
     *<p>参数说明：</p>
     * @param aimsBasicOrg 单位信息对象
     * @return
     *
     * @date   创建时间：2016年11月24日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public Map<String, Object> doEnable(AimsBasicOrg aimsBasicOrg);
    
    /**
     * <p>函数名称：doIsAnnualReport        </p>
     * <p>功能说明：根据单位ID 设置单位(单位)启用是否上报年报
     *
     * </p>
     *<p>参数说明：</p>
     * @param aimsBasicOrg 单位信息对象
     * @return
     *
     * @date   创建时间：2016年11月24日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public Map<String, Object> doIsAnnualReport(AimsBasicOrg aimsBasicOrg);
    
    /**
     * <p>函数名称：queryOneAssetSysConfig        </p>
     * <p>功能说明：获取级长信息
     *
     * </p>
     *<p>参数说明：</p>
     * @param appId       应用ID
     * @param configCode  配置编码
     * @return
     *
     * @date   创建时间：2016年12月20日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public AssetSysConfig queryOneAssetSysConfig(String appId, String configCode);
    
    /**
     * <p>函数名称：getAimsRegionList        </p>
     * <p>功能说明：获取区划列表
     *
     * </p>
     *<p>参数说明：</p>
     * @param status  状态
     * @return
     *
     * @date   创建时间：2016年12月26日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public List<AimsRegion> getAimsRegionList(String status);
    
    /**
     * <p>函数名称：queryAimsRegionPage        </p>
     * <p>功能说明：获取区划分页信息
     *
     * </p>
     *<p>参数说明：</p>
     * @param searcher
     * @param pageInfo
     * @param rngId   区划ID
     * @return
     *
     * @date   创建时间：2016年12月29日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public Page<AimsRegion> queryAimsRegionPage(Searcher searcher, Page<AimsRegion> pageInfo, Long rngId);

    /**
     * <p>函数名称：addRegion        </p>
     * <p>功能说明：新增区划信息
     *
     * </p>
     *<p>参数说明：</p>
     * @param aimsRegion 区划信息
     * @return
     *
     * @date   创建时间：2016年12月29日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public Map<String, Object> addRegion(AimsRegion aimsRegion);

    /**
     * <p>函数名称：queryOrgListBySql        </p>
     * <p>功能说明：根据sql语句加载单位列表
     *
     * </p>
     *<p>参数说明：</p>
     * @param sql sql语句
     * @return
     *
     * @date   创建时间：2017年1月10日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public List<AimsBasicOrg> queryOrgListBySql(String sql);
    
    public List<AimsBasicOrg> queryOrgListBySqlParams(String sql, Map params);
    
    /**
     * <p>函数名称：doUpdateFirstLogin        </p>
     * <p>功能说明：单位首次登陆系统补全信息
     *
     * </p>
     *<p>参数说明：</p>
     * @param aimsBasicOrg
     * @return
     *
     * @date   创建时间：2017年2月22日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public Map<String, Object> doUpdateFirstLogin(AimsBasicOrg aimsBasicOrg);
    
    
    /**
     * <p>函数名称：queryOrgPage        </p>
     * <p>功能说明：组织机构情况
     *
     * </p>
     *<p>参数说明：</p>
     * @param orgCode
     * @param pageInfo
     * @return
     *
     * @date   创建时间：2017年5月3日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public Page<AimsBasicOrg> queryOrgPage(String orgCode, Page<?> pageInfo);
    
    /**
     * <p>函数名称：searchListByKey        </p>
     * <p>功能说明：根据单位编码和查询节点值模糊查询单位列表
     *
     * </p>
     *<p>参数说明：</p>
     * @param orgCode   当前登录单位编码
     * @param _key      搜索节点值 
     * @return
     *
     * @date   创建时间：2017年5月9日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
     */
    public List<AimsBasicOrg> searchListByKey(String orgCode, String _key);
    
    /**
     * <p>函数名称：loadOrgByDrcSql        </p>
     * <p>功能说明：根据drcSql查询单位树
     *
     * </p>
     *<p>参数说明：</p>
     * @param orgCode 单位编码（drcSql至少需要一个参数）
     * @param status  状态
     * @return
     *
     * @date   创建时间：2017年11月10日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
     */
    public List<AimsBasicOrg> loadOrgByDrcSql(String orgCode, String status);
    
    /**
     * <p>函数名称：  loadOrgTreeByCode      </p>
     * <p>功能说明：根据单位编码和状态加载单位树
     *
     * </p>
     *<p>参数说明：</p>
     * @param orgCode  单位编码
     * @param status   状态
     * @return
     *
     * @date   创建时间：2017年11月10日
     * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
     */
    public List<AimsBasicOrg> loadOrgTreeByCode(String orgCode, String status);
}
 