package com.bosssoft.egov.asset.monitor.service.impl;


/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Thu Feb 23 16:04:50 CST 2017
 */

import java.util.List;

import com.bosssoft.egov.asset.monitor.entity.FabMonitorRecordUrlortype;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.bosssoft.egov.asset.monitor.service.FabMonitorRecordUrlortypeService;
import com.bosssoft.egov.asset.monitor.mapper.FabMonitorRecordUrlortypeMapper;


/**
 * 类说明: FabMonitorRecordUrlortypeService接口实现类. 
 *
 * 类用途：
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-02-23   jinbiao　　　新建
 * </pre>
 */
@Service
public class FabMonitorRecordUrlortypeServiceImpl implements FabMonitorRecordUrlortypeService {

	private static Logger logger = LoggerFactory.getLogger(FabMonitorRecordUrlortypeServiceImpl.class);

	// TODO 添加需要的Mapper
	@Autowired
	private FabMonitorRecordUrlortypeMapper fabMonitorRecordUrlortypeMapper;
	
	/**
	 *
	 * @param fabMonitorRecordUrlortype
	 */
	public void addFabMonitorRecordUrlortype(FabMonitorRecordUrlortype fabMonitorRecordUrlortype)  {
		fabMonitorRecordUrlortypeMapper.insert(fabMonitorRecordUrlortype);
	}

	/**
	 *
	 * @param fabMonitorRecordUrlortype
	 */
	public void delFabMonitorRecordUrlortype(FabMonitorRecordUrlortype fabMonitorRecordUrlortype)  {
		fabMonitorRecordUrlortypeMapper.deleteByPrimaryKey(fabMonitorRecordUrlortype);
	}

	/**
	 *
	 * @param fabMonitorRecordUrlortype
	 */
	public void updateFabMonitorRecordUrlortype(FabMonitorRecordUrlortype fabMonitorRecordUrlortype)  {
		fabMonitorRecordUrlortypeMapper.updateByPrimaryKey(fabMonitorRecordUrlortype);
	}

	/**
	 *
	 * @param fabMonitorRecordUrlortype
	 * @retrun
	 */
	public List<FabMonitorRecordUrlortype> getFabMonitorRecordUrlortypeList(FabMonitorRecordUrlortype fabMonitorRecordUrlortype)  {
		return null;
	}

	/**
	 *
	 * @param searcher
	 * @param page
	 * @retrun
	 */
	public Page<FabMonitorRecordUrlortype> queryFabMonitorRecordUrlortypePage(Searcher searcher, Page<FabMonitorRecordUrlortype> page)  {
		return null;
	}

	public FabMonitorRecordUrlortype queryFabMonitorRecordUrlortypeByBusType(String busType) {
		return fabMonitorRecordUrlortypeMapper.queryFabMonitorRecordUrlortypeByBusType(busType);
	}

	public List<FabMonitorRecordUrlortype> getFabMonitorRecordUrlortypeListAll(){
		return fabMonitorRecordUrlortypeMapper.getFabMonitorRecordUrlortypeListAll();
	}

}