/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * 2017年10月25日 下午12:01:20
 */
package com.bosssoft.egov.asset.ext.entity;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * 类说明: 自定义网格配置
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017年10月25日  chenzhibin  新建
 * </pre>
 */
@Table(name="asset_grid_cfg")
public class AssetGridCfg implements Serializable {

	private static final long serialVersionUID = 3894088701235240908L;

	/**
	 * 主键模板配置ID
	 */
	@Id
	@Column(name="CFG_ID")
	private Long cfgId;
	
	/**
	 * 模板配置名称
	 */
	@Column(name="CFG_NAME")
	private String cfgName;
	
	/**
	 * 用户编码
	 */
	@Column(name="USER_CODE")
	private String userCode;
	
	/**
	 * 网格唯一标识
	 */
	@Column(name="GRID_ID")
	private String gridId;
	
	/**
	 * 业务类型
	 */
	@Column(name="BIZ_TYPE")
	private String bizType;
	
	/**
	 * 业务类型名称
	 */
	@Column(name="BIZ_TYPE_NAME")
	private String bizTypeName;
	
	/**
	 * 网格头级次数
	 */
	@Column(name="LEVEL_COUNT")
	private Integer levelCount;
	
	/**
	 * 其他配置
	 */
	@Column(name="ATTR")
	private String attr;
	
	/**
	 * 状态:1:启用,0:禁用
	 */
	@Column(name="STATUS")
	private String status;
	
	/**
	 * 备注
	 */
	@Column(name="REMARK")
	private String remark;
	
	@Column(name="END_TIME")
	private String endTime;
	
	/**
	 * 使用状态，1：正在使用，0未使用
	 */
	@Column(name="USE_STATUS")
	private String useStatus;
	
	/**
	 * 列数据
	 */
	@Transient
	private List<AssetGridColCfg> columns;

	public AssetGridCfg(){
		
	}
	
	public AssetGridCfg(String gridId, String cfgName, String bizType, String bizTypeName, Integer levelCount) {
		this.gridId = gridId;
		this.cfgName = cfgName;
		this.bizType = bizType;
		this.bizTypeName = bizTypeName;
		this.levelCount = levelCount;
	}

	public AssetGridCfg(Long cfgId, String cfgName, String userCode, String gridId, String bizType,
			String bizTypeName, Integer levelCount) {
		this(gridId, cfgName, bizType, bizTypeName, levelCount);
		this.cfgId = cfgId;
		this.userCode = userCode;
	}

	public AssetGridCfg(String userCode, String gridId, String bizType) {
		this.userCode = userCode;
		this.gridId = gridId;
		this.bizType = bizType;
	}

	public AssetGridCfg(Long cfgId) {
		this.cfgId = cfgId;
	}

	public Long getCfgId() {
		return cfgId;
	}
	
	public void setCfgId(Long cfgId) {
		this.cfgId = cfgId;
	}
	
	public String getCfgName() {
		return cfgName;
	}
	
	public void setCfgName(String cfgName) {
		this.cfgName = cfgName;
	}

	public String getUserCode() {
		return userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getGridId() {
		return gridId;
	}
	
	public void setGridId(String gridId) {
		this.gridId = gridId;
	}

	public String getBizType() {
		return bizType;
	}

	public void setBizType(String bizType) {
		this.bizType = bizType;
	}

	public String getBizTypeName() {
		return bizTypeName;
	}

	public void setBizTypeName(String bizTypeName) {
		this.bizTypeName = bizTypeName;
	}

	public Integer getLevelCount() {
		return levelCount;
	}
	
	public void setLevelCount(Integer levelCount) {
		this.levelCount = levelCount;
	}
	
	public String getAttr() {
		return attr;
	}

	public void setAttr(String attr) {
		this.attr = attr;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	public String getEndTime() {
		return endTime;
	}
	
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}
	
	public List<AssetGridColCfg> getColumns() {
		return columns;
	}
	
	public void setColumns(List<AssetGridColCfg> columns) {
		this.columns = columns;
	}
	
	public String getUseStatus() {
		return useStatus;
	}
	
	public void setUseStatus(String useStatus) {
		this.useStatus = useStatus;
	}
	
	@Override
	public boolean equals(Object obj) {
		if(obj instanceof AssetGridCfg){
			AssetGridCfg grid = (AssetGridCfg) obj;
			if(grid.getCfgId().equals(this.getCfgId())){
				return true;
			}
		}
		return false;
	}
}
