
package com.bosssoft.asset.xm.sms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-13T18:08:37.330+08:00
 * Generated source version: 3.1.10
 * 
 */
public final class DxptWeb_DxptWebPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cn.xm.czj.dxpt", "DxptWebService");

    private DxptWeb_DxptWebPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DxptWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DxptWebService ss = new DxptWebService(wsdlURL, SERVICE_NAME);
        DxptWeb port = ss.getDxptWebPort();  
        
        {
        System.out.println("Invoking sendMsgNS...");
        java.lang.String _sendMsgNS_sendName = "";
        java.lang.String _sendMsgNS_sendDept = "";
        java.lang.String _sendMsgNS_content = "";
        java.lang.String _sendMsgNS_sendTime = "";
        java.lang.String _sendMsgNS_xtsqm = "";
        java.lang.String _sendMsgNS_recName = "";
        java.lang.String _sendMsgNS_recDept = "";
        java.lang.String _sendMsgNS_recPhone = "";
        java.lang.String _sendMsgNS_localTime = "";
        java.lang.String _sendMsgNS_qm = "";
        java.lang.String _sendMsgNS_qyhf = "";
        java.lang.String _sendMsgNS__return = port.sendMsgNS(_sendMsgNS_sendName, _sendMsgNS_sendDept, _sendMsgNS_content, _sendMsgNS_sendTime, _sendMsgNS_xtsqm, _sendMsgNS_recName, _sendMsgNS_recDept, _sendMsgNS_recPhone, _sendMsgNS_localTime, _sendMsgNS_qm, _sendMsgNS_qyhf);
        System.out.println("sendMsgNS.result=" + _sendMsgNS__return);


        }
        {
        System.out.println("Invoking getRptBySendIdAndPhoneNS...");
        java.lang.String _getRptBySendIdAndPhoneNS_sendId = "";
        java.lang.String _getRptBySendIdAndPhoneNS_recPhone = "";
        java.lang.String _getRptBySendIdAndPhoneNS__return = port.getRptBySendIdAndPhoneNS(_getRptBySendIdAndPhoneNS_sendId, _getRptBySendIdAndPhoneNS_recPhone);
        System.out.println("getRptBySendIdAndPhoneNS.result=" + _getRptBySendIdAndPhoneNS__return);


        }
        {
        System.out.println("Invoking sendMsgMassNS...");
        java.lang.String _sendMsgMassNS_sendName = "";
        java.lang.String _sendMsgMassNS_sendDept = "";
        java.lang.String _sendMsgMassNS_content = "";
        java.lang.String _sendMsgMassNS_sendTime = "";
        java.lang.String _sendMsgMassNS_xtsqm = "";
        java.lang.String _sendMsgMassNS_jsrString = "";
        java.lang.String _sendMsgMassNS_localTime = "";
        java.lang.String _sendMsgMassNS_qm = "";
        java.lang.String _sendMsgMassNS_qyhf = "";
        java.lang.String _sendMsgMassNS__return = port.sendMsgMassNS(_sendMsgMassNS_sendName, _sendMsgMassNS_sendDept, _sendMsgMassNS_content, _sendMsgMassNS_sendTime, _sendMsgMassNS_xtsqm, _sendMsgMassNS_jsrString, _sendMsgMassNS_localTime, _sendMsgMassNS_qm, _sendMsgMassNS_qyhf);
        System.out.println("sendMsgMassNS.result=" + _sendMsgMassNS__return);


        }
        {
        System.out.println("Invoking getRptBySendIdNS...");
        java.lang.String _getRptBySendIdNS_sendId = "";
        java.lang.String _getRptBySendIdNS__return = port.getRptBySendIdNS(_getRptBySendIdNS_sendId);
        System.out.println("getRptBySendIdNS.result=" + _getRptBySendIdNS__return);


        }
        {
        System.out.println("Invoking getMoBySendIdAndPhone...");
        java.lang.String _getMoBySendIdAndPhone_sendId = "";
        java.lang.String _getMoBySendIdAndPhone_phone = "";
        java.lang.String _getMoBySendIdAndPhone_xtsqm = "";
        java.lang.String _getMoBySendIdAndPhone__return = port.getMoBySendIdAndPhone(_getMoBySendIdAndPhone_sendId, _getMoBySendIdAndPhone_phone, _getMoBySendIdAndPhone_xtsqm);
        System.out.println("getMoBySendIdAndPhone.result=" + _getMoBySendIdAndPhone__return);


        }
        {
        System.out.println("Invoking sendMsgMass...");
        java.lang.String _sendMsgMass_sendName = "";
        java.lang.String _sendMsgMass_sendDept = "";
        java.lang.String _sendMsgMass_content = "";
        java.lang.String _sendMsgMass_sendTime = "";
        java.lang.String _sendMsgMass_xtsqm = "";
        java.lang.String _sendMsgMass_jsrString = "";
        java.lang.String _sendMsgMass_localTime = "";
        java.lang.String _sendMsgMass_qm = "";
        java.lang.String _sendMsgMass_qyhf = "";
        java.lang.String _sendMsgMass__return = port.sendMsgMass(_sendMsgMass_sendName, _sendMsgMass_sendDept, _sendMsgMass_content, _sendMsgMass_sendTime, _sendMsgMass_xtsqm, _sendMsgMass_jsrString, _sendMsgMass_localTime, _sendMsgMass_qm, _sendMsgMass_qyhf);
        System.out.println("sendMsgMass.result=" + _sendMsgMass__return);


        }
        {
        System.out.println("Invoking updateTxlNS...");
        java.lang.String _updateTxlNS_qzxx = "";
        java.lang.String _updateTxlNS_lxrxx = "";
        java.lang.String _updateTxlNS__return = port.updateTxlNS(_updateTxlNS_qzxx, _updateTxlNS_lxrxx);
        System.out.println("updateTxlNS.result=" + _updateTxlNS__return);


        }
        {
        System.out.println("Invoking getRptBySendIdAndPhone...");
        java.lang.String _getRptBySendIdAndPhone_sendId = "";
        java.lang.String _getRptBySendIdAndPhone_recPhone = "";
        java.lang.String _getRptBySendIdAndPhone__return = port.getRptBySendIdAndPhone(_getRptBySendIdAndPhone_sendId, _getRptBySendIdAndPhone_recPhone);
        System.out.println("getRptBySendIdAndPhone.result=" + _getRptBySendIdAndPhone__return);


        }
        {
        System.out.println("Invoking updateTxl...");
        java.lang.String _updateTxl_qzxx = "";
        java.lang.String _updateTxl_lxrxx = "";
        java.lang.String _updateTxl__return = port.updateTxl(_updateTxl_qzxx, _updateTxl_lxrxx);
        System.out.println("updateTxl.result=" + _updateTxl__return);


        }
        {
        System.out.println("Invoking getMoBySendId...");
        java.lang.String _getMoBySendId_sendId = "";
        java.lang.String _getMoBySendId_xtsqm = "";
        java.lang.String _getMoBySendId__return = port.getMoBySendId(_getMoBySendId_sendId, _getMoBySendId_xtsqm);
        System.out.println("getMoBySendId.result=" + _getMoBySendId__return);


        }
        {
        System.out.println("Invoking getMoBySendIdAndPhoneNS...");
        java.lang.String _getMoBySendIdAndPhoneNS_sendId = "";
        java.lang.String _getMoBySendIdAndPhoneNS_phone = "";
        java.lang.String _getMoBySendIdAndPhoneNS_xtsqm = "";
        java.lang.String _getMoBySendIdAndPhoneNS__return = port.getMoBySendIdAndPhoneNS(_getMoBySendIdAndPhoneNS_sendId, _getMoBySendIdAndPhoneNS_phone, _getMoBySendIdAndPhoneNS_xtsqm);
        System.out.println("getMoBySendIdAndPhoneNS.result=" + _getMoBySendIdAndPhoneNS__return);


        }
        {
        System.out.println("Invoking getMoBySendIdNS...");
        java.lang.String _getMoBySendIdNS_sendId = "";
        java.lang.String _getMoBySendIdNS_xtsqm = "";
        java.lang.String _getMoBySendIdNS__return = port.getMoBySendIdNS(_getMoBySendIdNS_sendId, _getMoBySendIdNS_xtsqm);
        System.out.println("getMoBySendIdNS.result=" + _getMoBySendIdNS__return);


        }
        {
        System.out.println("Invoking getRptById...");
        java.lang.String _getRptById_sendId = "";
        java.lang.String _getRptById__return = port.getRptById(_getRptById_sendId);
        System.out.println("getRptById.result=" + _getRptById__return);


        }
        {
        System.out.println("Invoking sendMsg...");
        java.lang.String _sendMsg_sendName = "";
        java.lang.String _sendMsg_sendDept = "";
        java.lang.String _sendMsg_content = "";
        java.lang.String _sendMsg_sendTime = "";
        java.lang.String _sendMsg_xtsqm = "";
        java.lang.String _sendMsg_recName = "";
        java.lang.String _sendMsg_recDept = "";
        java.lang.String _sendMsg_recPhone = "";
        java.lang.String _sendMsg_localTime = "";
        java.lang.String _sendMsg_qm = "";
        java.lang.String _sendMsg_qyhf = "";
        java.lang.String _sendMsg__return = port.sendMsg(_sendMsg_sendName, _sendMsg_sendDept, _sendMsg_content, _sendMsg_sendTime, _sendMsg_xtsqm, _sendMsg_recName, _sendMsg_recDept, _sendMsg_recPhone, _sendMsg_localTime, _sendMsg_qm, _sendMsg_qyhf);
        System.out.println("sendMsg.result=" + _sendMsg__return);


        }

        System.exit(0);
    }

}
