package com.bosssoft.asset.xm.sms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-13T18:08:37.376+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "DxptWebService", 
                  wsdlLocation = "http://199.199.199.11:8089/xmczmsg/webservice?wsdl",
                  targetNamespace = "http://cn.xm.czj.dxpt") 
public class DxptWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cn.xm.czj.dxpt", "DxptWebService");
    public final static QName DxptWebPort = new QName("http://cn.xm.czj.dxpt", "DxptWebPort");
    static {
        URL url = null;
        try {
            url = new URL("http://199.199.199.11:8089/xmczmsg/webservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DxptWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://199.199.199.11:8089/xmczmsg/webservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DxptWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DxptWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DxptWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DxptWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DxptWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DxptWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DxptWeb
     */
    @WebEndpoint(name = "DxptWebPort")
    public DxptWeb getDxptWebPort() {
        return super.getPort(DxptWebPort, DxptWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DxptWeb
     */
    @WebEndpoint(name = "DxptWebPort")
    public DxptWeb getDxptWebPort(WebServiceFeature... features) {
        return super.getPort(DxptWebPort, DxptWeb.class, features);
    }

}
