/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sun Jan 22 13:31:09 CST 2017
 */
package com.bosssoft.egov.asset.template.mapper;

import org.apache.ibatis.annotations.Param;

import com.bosssoft.egov.asset.template.entity.AimsTemplateDetail;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.persistence.common.Mapper;
import com.bosssoft.platform.common.lang.data.Searcher;

/**
 * 类说明:  Mapper接口（ Mapper层） .
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-22   Administrator　　　新建
 * </pre>

 */

public interface AimsTemplateDetailMapper extends Mapper<AimsTemplateDetail>{



/**
	 * 
	 * 查询分页.
	 *	`
	 * @param searcher 查询条件
	 * @param pageable 分页信息
	 * @return AimsTemplateDetailPage列表
	 * @throws BusinessException 自定义异常
	 *
	 */
	public Page<AimsTemplateDetail> queryAimsTemplateDetailPage(@Param("searcher")Searcher searcher,@Param("page")Page<AimsTemplateDetail> page);
			
	/**
	 * <p>函数名称：  queryTemplateDetailPage      </p>
	 * <p>功能说明：加载模板分页信息（单位自定义模板和默认模板）
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param searcher
	 * @param page
	 * @param moduleId
	 * @param orgId
	 * @return
	 *
	 * @date   创建时间：2017年11月7日
	 * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
	 */
	public Page<AimsTemplateDetail> queryTemplateDetailPage(@Param("searcher")Searcher searcher,@Param("page")Page<AimsTemplateDetail> page,
				@Param("moduleId") Long moduleId, @Param("orgId") Long orgId);
	
	/**
	 * <p>函数名称：updateById        </p>
	 * <p>功能说明：根据id修改模板信息
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param aimsTemplateDetail
	 * @return
	 *
	 * @date   创建时间：2017年2月14日
	 * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn) 
	 */
	public int updateById(AimsTemplateDetail aimsTemplateDetail);
	
	/**
	 * <p>函数名称：deleteById        </p>
	 * <p>功能说明：根据id删除模板信息
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param aimsTemplateDetail
	 * @return
	 *
	 * @date   创建时间：2017年11月7日
	 * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
	 */
	public int deleteById(AimsTemplateDetail aimsTemplateDetail);
	
	/**
	 * <p>函数名称：  queryOne      </p>
	 * <p>功能说明：根据moduleItemId查询模板信息
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param moduleItemId
	 * @return
	 *
	 * @date   创建时间：2017年11月7日
	 * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
	 */
	public AimsTemplateDetail queryOne(@Param("moduleItemId") Long moduleItemId);
	
	/**
	 * <p>函数名称：queryTemplateDetailPageByOrgId        </p>
	 * <p>功能说明：根据单位id加载模板列表（单位自定义模板和除单位自定义模板以外的默认模板）
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param searcher
	 * @param page
	 * @param moduleId
	 * @param orgId
	 * @return
	 *
	 * @date   创建时间：2017年11月7日
	 * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
	 */
	public Page<AimsTemplateDetail> queryTemplateDetailPageByOrgId(@Param("searcher") Searcher searcher,@Param("page") Page<AimsTemplateDetail> page,
			@Param("moduleId") Long moduleId, @Param("orgId") Long orgId);

}