/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Mon Jan 16 11:24:16 CST 2017
 */
package com.bosssoft.egov.asset.monitor.entity;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 预警记录表对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-01-16   Administrator　　　新建
 * </pre>
 */
 @Table(name = "FAB_MONITOR_RECORD")
public class FabMonitorRecord implements java.io.Serializable {

	private static final long serialVersionUID = 170116112453862L;
	
	// Fields
	
	/**
	 * 主键.
	 */
	@Id
    @Column(name = "FID")
	private String fid;
	/**
	 * 区划ID.
	 */
    @Column(name = "FRGNID")
	private String frgnid;
	/**
	 * 监控事项ID.
	 */
    @Column(name = "FEVTID")
	private String fevtid;
	/**
	 * 监控事项编码.
	 */
    @Column(name = "FEVTCODE")
	private String fevtcode;
	/**
	 * 监控事项名称.
	 */
    @Column(name = "FEVTNAME")
	private String fevtname;
	/**
	 * 监管机构ID.
	 */
    @Column(name = "FMCMID")
	private String fmcmid;
	/**
	 * 预警监控机构编码.
	 */
    @Column(name = "FMCMCODE")
	private String fmcmcode;
	/**
	 * 预警监控机构名称.
	 */
    @Column(name = "FMCMNAME")
	private String fmcmname;
	/**
	 * 产生预警记录的业务数据ID.
	 */
    @Column(name = "FBUSIID")
	private String fbusiid;
	/**
	 * 预警发生机构ID.
	 */
    @Column(name = "FOMONITORID")
	private String fomonitorid;
	/**
	 * 发生预警机构编码.
	 */
    @Column(name = "FOMONITORCODE")
	private String fomonitorcode;
	/**
	 * 发生预警机构名称.
	 */
    @Column(name = "FOMONITORNAME")
	private String fomonitorname;
	/**
	 * 处理机构ID.
	 */
    @Column(name = "FHNDLORGID")
	private String fhndlorgid;
	/**
	 * 处理机构编码.
	 */
    @Column(name = "FHNDLORGCODE")
	private String fhndlorgcode;
	/**
	 * 处理机构名称.
	 */
    @Column(name = "FHNDLORGNAME")
	private String fhndlorgname;
	/**
	 * 预警内容.
	 */
    @Column(name = "FMNTCONT")
	private String fmntcont;
	/**
	 * 预警发生日期.
	 */
    @Column(name = "FMNTDATE")
	private String fmntdate;
	/**
	 * 预警发生时间.
	 */
    @Column(name = "FMNTTIME")
	private String fmnttime;
	/**
	 * 处理状态（0：否，1：是）.
	 */
    @Column(name = "FISHNDL")
	private Integer fishndl;
	/**
	 * 处理人员ID.
	 */
    @Column(name = "FHNDLID")
	private String fhndlid;
	/**
	 * 处理人员.
	 */
    @Column(name = "FHNDLNAME")
	private String fhndlname;
	/**
	 * 处理时间.
	 */
    @Column(name = "FHNDLTIME")
	private String fhndltime;
	/**
	 * 处理日期.
	 */
    @Column(name = "FHNDLDATE")
	private String fhndldate;
	/**
	 * 预警记录处理说明.
	 */
    @Column(name = "FHNDLDESC")
	private String fhndldesc;
	/**
	 * 是否关闭（0：否，1：是）.
	 */
    @Column(name = "FISCLOSE")
	private Integer fisclose;
	/**
	 * 关闭人ID.
	 */
    @Column(name = "FCLSMANID")
	private String fclsmanid;
	/**
	 * 关闭人.
	 */
    @Column(name = "FCLSMAN")
	private String fclsman;
	/**
	 * 关闭日期.
	 */
    @Column(name = "FCLSDATE")
	private String fclsdate;
	/**
	 * 关闭时间.
	 */
    @Column(name = "FCLSTIME")
	private String fclstime;
	/**
	 * 最后修改时间.
	 */
    @Column(name = "FUPDATETIME")
	private String fupdatetime;
	/**
	 * 变更类型编码.
	 */
    @Column(name = "FALTERCODE")
	private String faltercode;
	/**
	 * 版本号.
	 */
    @Column(name = "FVERSION")
	private Long fversion;
    /**
     * 点击数（大于0则就已被查看过）.
     */
    @Column(name = "FCLICK")
    private Long fclick;
    
    /**
     * 是否进行细分.
     */
    @Column(name = "PTYPE")
    private String ptype;
	
    /**
     * 是否为结果
     */
    @Column(name = "ISRESULT")
    private String isResult;
    
    /**
     * 是否为结果
     */
    @Column(name = "FAVORITEOPTION")
    private String favoriteOption;
    
    /**
     * 明细id
     */
    @Column(name = "DETAIL_ID")
    private String detailId;
    /**
     * 明细id
     */
    @Column(name = "OPTION_ID")
    private String optionId;
    /**
     * 类型
     */
    @Column(name = "TYPE")
    private String type;
    /**
     * 类型名称
     */
    @Column(name = "TYPE_NAME")
    private String typeName;
    /**
     * 类型名称
     */
    @Column(name = "PTYPE_NAME")
    private String ptypeName;
    /**
     * 类型名称
     */
    @Column(name = "URL")
    private String url;
    /**
     * 类型名称
     */
    @Column(name = "PARAM1")
    private String param1;
    /**
     * 类型名称
     */
    @Column(name = "PARAM2")
    private String param2;
    /**
     * 类型名称
     */
    @Column(name = "PARAM3")
    private String param3;
    /**
     * 是否保存最新记录，默认1只保存最新记录
     */
    @Column(name = "ISNEW")
    private String isNew;
	// Constructors
 
    /** default constructor */
	public FabMonitorRecord() {
		this.fclick = 0l;
	}

	/**
	 * 主键.
	 * @return
	 */
	public String getFid() {
		return this.fid;
	}

	/**
	 * 主键.
	 * @param fid
	 */
	public void setFid(String fid) {
		this.fid = fid;
	}

	/**
	 * 区划ID.
	 * @return
	 */
	public String getFrgnid() {
		return this.frgnid;
	}

	/**
	 * 区划ID.
	 * @param frgnid
	 */
	public void setFrgnid(String frgnid) {
		this.frgnid = frgnid;
	}

	/**
	 * 监控事项ID.
	 * @return
	 */
	public String getFevtid() {
		return this.fevtid;
	}

	/**
	 * 监控事项ID.
	 * @param fevtid
	 */
	public void setFevtid(String fevtid) {
		this.fevtid = fevtid;
	}

	/**
	 * 监控事项编码.
	 * @return
	 */
	public String getFevtcode() {
		return this.fevtcode;
	}

	/**
	 * 监控事项编码.
	 * @param fevtcode
	 */
	public void setFevtcode(String fevtcode) {
		this.fevtcode = fevtcode;
	}

	/**
	 * 监控事项名称.
	 * @return
	 */
	public String getFevtname() {
		return this.fevtname;
	}

	/**
	 * 监控事项名称.
	 * @param fevtname
	 */
	public void setFevtname(String fevtname) {
		this.fevtname = fevtname;
	}

	/**
	 * 监管机构ID.
	 * @return
	 */
	public String getFmcmid() {
		return this.fmcmid;
	}

	/**
	 * 监管机构ID.
	 * @param fmcmid
	 */
	public void setFmcmid(String fmcmid) {
		this.fmcmid = fmcmid;
	}

	/**
	 * 预警监控机构编码.
	 * @return
	 */
	public String getFmcmcode() {
		return this.fmcmcode;
	}

	/**
	 * 预警监控机构编码.
	 * @param fmcmcode
	 */
	public void setFmcmcode(String fmcmcode) {
		this.fmcmcode = fmcmcode;
	}

	/**
	 * 预警监控机构名称.
	 * @return
	 */
	public String getFmcmname() {
		return this.fmcmname;
	}

	/**
	 * 预警监控机构名称.
	 * @param fmcmname
	 */
	public void setFmcmname(String fmcmname) {
		this.fmcmname = fmcmname;
	}

	/**
	 * 产生预警记录的业务数据ID.
	 * @return
	 */
	public String getFbusiid() {
		return this.fbusiid;
	}

	/**
	 * 产生预警记录的业务数据ID.
	 * @param fbusiid
	 */
	public void setFbusiid(String fbusiid) {
		this.fbusiid = fbusiid;
	}

	/**
	 * 预警发生机构ID.
	 * @return
	 */
	public String getFomonitorid() {
		return this.fomonitorid;
	}

	/**
	 * 预警发生机构ID.
	 * @param fomonitorid
	 */
	public void setFomonitorid(String fomonitorid) {
		this.fomonitorid = fomonitorid;
	}

	/**
	 * 发生预警机构编码.
	 * @return
	 */
	public String getFomonitorcode() {
		return this.fomonitorcode;
	}

	/**
	 * 发生预警机构编码.
	 * @param fomonitorcode
	 */
	public void setFomonitorcode(String fomonitorcode) {
		this.fomonitorcode = fomonitorcode;
	}

	/**
	 * 发生预警机构名称.
	 * @return
	 */
	public String getFomonitorname() {
		return this.fomonitorname;
	}

	/**
	 * 发生预警机构名称.
	 * @param fomonitorname
	 */
	public void setFomonitorname(String fomonitorname) {
		this.fomonitorname = fomonitorname;
	}

	/**
	 * 处理机构ID.
	 * @return
	 */
	public String getFhndlorgid() {
		return this.fhndlorgid;
	}

	/**
	 * 处理机构ID.
	 * @param fhndlorgid
	 */
	public void setFhndlorgid(String fhndlorgid) {
		this.fhndlorgid = fhndlorgid;
	}

	/**
	 * 处理机构编码.
	 * @return
	 */
	public String getFhndlorgcode() {
		return this.fhndlorgcode;
	}

	/**
	 * 处理机构编码.
	 * @param fhndlorgcode
	 */
	public void setFhndlorgcode(String fhndlorgcode) {
		this.fhndlorgcode = fhndlorgcode;
	}

	/**
	 * 处理机构名称.
	 * @return
	 */
	public String getFhndlorgname() {
		return this.fhndlorgname;
	}

	/**
	 * 处理机构名称.
	 * @param fhndlorgname
	 */
	public void setFhndlorgname(String fhndlorgname) {
		this.fhndlorgname = fhndlorgname;
	}

	/**
	 * 预警内容.
	 * @return
	 */
	public String getFmntcont() {
		return this.fmntcont;
	}

	/**
	 * 预警内容.
	 * @param fmntcont
	 */
	public void setFmntcont(String fmntcont) {
		this.fmntcont = fmntcont;
	}

	/**
	 * 预警发生日期.
	 * @return
	 */
	public String getFmntdate() {
		return this.fmntdate;
	}

	/**
	 * 预警发生日期.
	 * @param fmntdate
	 */
	public void setFmntdate(String fmntdate) {
		this.fmntdate = fmntdate;
	}

	/**
	 * 预警发生时间.
	 * @return
	 */
	public String getFmnttime() {
		return this.fmnttime;
	}

	/**
	 * 预警发生时间.
	 * @param fmnttime
	 */
	public void setFmnttime(String fmnttime) {
		this.fmnttime = fmnttime;
	}

	/**
	 * 处理状态（0：否，1：是）.
	 * @return
	 */
	public Integer getFishndl() {
		return this.fishndl;
	}

	/**
	 * 处理状态（0：否，1：是）.
	 * @param fishndl
	 */
	public void setFishndl(Integer fishndl) {
		this.fishndl = fishndl;
	}

	/**
	 * 处理人员ID.
	 * @return
	 */
	public String getFhndlid() {
		return this.fhndlid;
	}

	/**
	 * 处理人员ID.
	 * @param fhndlid
	 */
	public void setFhndlid(String fhndlid) {
		this.fhndlid = fhndlid;
	}

	/**
	 * 处理人员.
	 * @return
	 */
	public String getFhndlname() {
		return this.fhndlname;
	}

	/**
	 * 处理人员.
	 * @param fhndlname
	 */
	public void setFhndlname(String fhndlname) {
		this.fhndlname = fhndlname;
	}

	/**
	 * 处理时间.
	 * @return
	 */
	public String getFhndltime() {
		return this.fhndltime;
	}

	/**
	 * 处理时间.
	 * @param fhndltime
	 */
	public void setFhndltime(String fhndltime) {
		this.fhndltime = fhndltime;
	}

	/**
	 * 处理日期.
	 * @return
	 */
	public String getFhndldate() {
		return this.fhndldate;
	}

	/**
	 * 处理日期.
	 * @param fhndldate
	 */
	public void setFhndldate(String fhndldate) {
		this.fhndldate = fhndldate;
	}

	/**
	 * 预警记录处理说明.
	 * @return
	 */
	public String getFhndldesc() {
		return this.fhndldesc;
	}

	/**
	 * 预警记录处理说明.
	 * @param fhndldesc
	 */
	public void setFhndldesc(String fhndldesc) {
		this.fhndldesc = fhndldesc;
	}

	/**
	 * 是否关闭（0：否，1：是）.
	 * @return
	 */
	public Integer getFisclose() {
		return this.fisclose;
	}

	/**
	 * 是否关闭（0：否，1：是）.
	 * @param fisclose
	 */
	public void setFisclose(Integer fisclose) {
		this.fisclose = fisclose;
	}

	/**
	 * 关闭人ID.
	 * @return
	 */
	public String getFclsmanid() {
		return this.fclsmanid;
	}

	/**
	 * 关闭人ID.
	 * @param fclsmanid
	 */
	public void setFclsmanid(String fclsmanid) {
		this.fclsmanid = fclsmanid;
	}

	/**
	 * 关闭人.
	 * @return
	 */
	public String getFclsman() {
		return this.fclsman;
	}

	/**
	 * 关闭人.
	 * @param fclsman
	 */
	public void setFclsman(String fclsman) {
		this.fclsman = fclsman;
	}

	/**
	 * 关闭日期.
	 * @return
	 */
	public String getFclsdate() {
		return this.fclsdate;
	}

	/**
	 * 关闭日期.
	 * @param fclsdate
	 */
	public void setFclsdate(String fclsdate) {
		this.fclsdate = fclsdate;
	}

	/**
	 * 关闭时间.
	 * @return
	 */
	public String getFclstime() {
		return this.fclstime;
	}

	/**
	 * 关闭时间.
	 * @param fclstime
	 */
	public void setFclstime(String fclstime) {
		this.fclstime = fclstime;
	}

	/**
	 * 最后修改时间.
	 * @return
	 */
	@JsonFormat(pattern = "yyyy-MM-dd")
	public String getFupdatetime() {
		return this.fupdatetime;
	}

	/**
	 * 最后修改时间.
	 * @param fupdatetime
	 */
	public void setFupdatetime(String fupdatetime) {
		this.fupdatetime = fupdatetime;
	}

	/**
	 * 变更类型编码.
	 * @return
	 */
	public String getFaltercode() {
		return this.faltercode;
	}

	/**
	 * 变更类型编码.
	 * @param faltercode
	 */
	public void setFaltercode(String faltercode) {
		this.faltercode = faltercode;
	}

	/**
	 * 版本号.
	 * @return
	 */
	public Long getFversion() {
		return this.fversion;
	}

	/**
	 * 版本号.
	 * @param fversion
	 */
	public void setFversion(Long fversion) {
		this.fversion = fversion;
	}

	public Long getFclick() {
		return fclick;
	}

	public void setFclick(Long fclick) {
		this.fclick = fclick;
	}

	public String getPtype() {
		return ptype;
	}

	public void setPtype(String ptype) {
		this.ptype = ptype;
	}

	public String getIsResult() {
		return isResult;
	}

	public void setIsResult(String isResult) {
		this.isResult = isResult;
	}

	public String getFavoriteOption() {
		return favoriteOption;
	}

	public  void setFavoriteOption(String favoriteOption) {
		this.favoriteOption = favoriteOption;
	}

	public String getDetailId() {
		return detailId;
	}

	public void setDetailId(String detailId) {
		this.detailId = detailId;
	}

	public String getOptionId() {
		return optionId;
	}

	public void setOptionId(String optionId) {
		this.optionId = optionId;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getPtypeName() {
		return ptypeName;
	}

	public void setPtypeName(String ptypeName) {
		this.ptypeName = ptypeName;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getParam1() {
		return param1;
	}

	public void setParam1(String param1) {
		this.param1 = param1;
	}

	public String getParam2() {
		return param2;
	}

	public void setParam2(String param2) {
		this.param2 = param2;
	}

	public String getParam3() {
		return param3;
	}

	public void setParam3(String param3) {
		this.param3 = param3;
	}

	public String getIsNew() {
		return isNew;
	}

	public void setIsNew(String isNew) {
		this.isNew = isNew;
	}
	
}