/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * 2017年10月25日 下午3:02:27
 */
package com.bosssoft.egov.asset.ext.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bosssoft.egov.asset.ext.entity.AssetGridCfg;
import com.bosssoft.platform.persistence.common.Mapper;

/**
 * 类说明: 网格配置mapper接口
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017年10月25日  chenzhibin  新建
 * </pre>
 */
public interface AssetGridCfgMapper extends Mapper<AssetGridCfg> {

	/**
	 * 根据当前用户获取某个业务的网格配置
	 * @param grid
	 * @return
	 */
	List<AssetGridCfg> getGridCfgByUserGrid(AssetGridCfg grid);

	/**
	 * 清空用户对应网格配置
	 * @param grid
	 */
	int clearGridCfg(AssetGridCfg grid);

	/**
	 * <p>功能说明：根据网格配置模板ID获取配置信息
	 * </p>
	 * <p>参数说明：
	 * @param cfgId
	 * @return
	 * </p>
	 *
	 * @date	创建时间：2017年12月19日
	 * @author	作者：chenzhibin
	 */
	AssetGridCfg getGridCfgByCfgId(@Param("cfgId")Long cfgId);

	/**
	 * <p>功能说明：重置网格配置使用状态
	 * </p>
	 * <p>参数说明：
	 * @param grid 对应用户操作的某个网格配置信息
	 * @return
	 * </p>
	 *
	 * @date	创建时间：2017年12月20日
	 * @author	作者：chenzhibin
	 */
	int resetUseStatus(AssetGridCfg grid);
}
