/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sun Jul 16 11:22:09 CST 2017
 */
package com.bosssoft.egov.asset.card.entity.basic;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 卡片位置/地址属性表对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-07-16   xiedeshou　　　新建
 * </pre>
 */
 @Table(name = "AIMS_CARD_ATTR_LBS")
public class AimsCardAttrLbs implements java.io.Serializable {

	private static final long serialVersionUID = 170716112228621L;
	
	// Fields
	
	/**
	 * 唯一id.
	 */
    @Column(name = "ID")
    @Id
	private Long id;
	/**
	 * 关联卡片id.
	 */
    @Column(name = "ASSET_ID")
	private Long assetId;
    
    /**
	 * .
	 */
    @Column(name = "PROVINCE_PID")
	private String provincePid;
	/**
	 * .
	 */
    @Column(name = "PROVINCE_ID")
	private String provinceId;
	/**
	 * .
	 */
    @Column(name = "PROVINCE_CODE")
	private String provinceCode;
	/**
	 * .
	 */
    @Column(name = "PROVINCE_NAME")
	private String provinceName;
	/**
	 * .
	 */
    @Column(name = "CITY_ID")
	private String cityId;
	/**
	 * .
	 */
    @Column(name = "CITY_CODE")
	private String cityCode;
	/**
	 * .
	 */
    @Column(name = "CITY_NAME")
	private String cityName;
	/**
	 * .
	 */
    @Column(name = "DISTRICT_ID")
	private String districtId;
	/**
	 * .
	 */
    @Column(name = "DISTRICT_CODE")
	private String districtCode;
	/**
	 * .
	 */
    @Column(name = "DISTRICT_NAME")
	private String districtName;
	/**
	 * .
	 */
    @Column(name = "STREET_ID")
	private String streetId;
	/**
	 * .
	 */
    @Column(name = "STREET_CODE")
	private String streetCode;
	/**
	 * .
	 */
    @Column(name = "STREET_NAME")
	private String streetName;
	/**
	 * 详细地址.
	 */
    @Column(name = "ADDRESS")
	private String address;
	/**
	 * 邮编.
	 */
    @Column(name = "ZIP_CODE")
	private String zipCode;
	/**
	 * 经度.
	 */
    @Column(name = "LONGITUDE")
	private Double longitude;
	/**
	 * 纬度.
	 */
    @Column(name = "LATITUDE")
	private Double latitude;
	/**
	 * .
	 */
    @Column(name = "CREATOR_ID")
	private String creatorId;
	/**
	 * .
	 */
    @Column(name = "CREATOR")
	private String creator;
	/**
	 * .
	 */
    @Column(name = "CREATE_DATE")
	private String createDate;
	/**
	 * .
	 */
    @Column(name = "CREATE_TIME")
	private String createTime;
	/**
	 * .
	 */
    @Column(name = "REMARK")
	private String remark;
	
	// Constructors
 
    /** default constructor */
	public AimsCardAttrLbs() {
	}

	/**
	 * 唯一id.
	 * @return
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * 唯一id.
	 * @param id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * 关联卡片id.
	 * @return
	 */
	public Long getAssetId() {
		return this.assetId;
	}

	/**
	 * 关联卡片id.
	 * @param assetId
	 */
	public void setAssetId(Long assetId) {
		this.assetId = assetId;
	}

	/**
	 * .
	 * @return
	 */
	public String getProvinceId() {
		return this.provinceId;
	}

	/**
	 * .
	 * @param provinceId
	 */
	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	/**
	 * .
	 * @return
	 */
	public String getProvinceCode() {
		return this.provinceCode;
	}

	/**
	 * .
	 * @param provinceCode
	 */
	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}

	/**
	 * .
	 * @return
	 */
	public String getProvinceName() {
		return this.provinceName;
	}

	/**
	 * .
	 * @param provinceName
	 */
	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	/**
	 * .
	 * @return
	 */
	public String getCityId() {
		return this.cityId;
	}

	/**
	 * .
	 * @param cityId
	 */
	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	/**
	 * .
	 * @return
	 */
	public String getCityCode() {
		return this.cityCode;
	}

	/**
	 * .
	 * @param cityCode
	 */
	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	/**
	 * .
	 * @return
	 */
	public String getCityName() {
		return this.cityName;
	}

	/**
	 * .
	 * @param cityName
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	/**
	 * .
	 * @return
	 */
	public String getDistrictId() {
		return this.districtId;
	}

	/**
	 * .
	 * @param districtId
	 */
	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	/**
	 * .
	 * @return
	 */
	public String getDistrictCode() {
		return this.districtCode;
	}

	/**
	 * .
	 * @param districtCode
	 */
	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode;
	}

	/**
	 * .
	 * @return
	 */
	public String getDistrictName() {
		return this.districtName;
	}

	/**
	 * .
	 * @param districtName
	 */
	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	/**
	 * .
	 * @return
	 */
	public String getStreetId() {
		return this.streetId;
	}

	/**
	 * .
	 * @param streetId
	 */
	public void setStreetId(String streetId) {
		this.streetId = streetId;
	}

	/**
	 * .
	 * @return
	 */
	public String getStreetCode() {
		return this.streetCode;
	}

	/**
	 * .
	 * @param streetCode
	 */
	public void setStreetCode(String streetCode) {
		this.streetCode = streetCode;
	}

	/**
	 * .
	 * @return
	 */
	public String getStreetName() {
		return this.streetName;
	}

	/**
	 * .
	 * @param streetName
	 */
	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	/**
	 * 详细地址.
	 * @return
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * 详细地址.
	 * @param address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * 邮编.
	 * @return
	 */
	public String getZipCode() {
		return this.zipCode;
	}

	/**
	 * 邮编.
	 * @param zipCode
	 */
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	/**
	 * 经度.
	 * @return
	 */
	public Double getLongitude() {
		return this.longitude;
	}

	/**
	 * 经度.
	 * @param longitude
	 */
	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	/**
	 * 纬度.
	 * @return
	 */
	public Double getLatitude() {
		return this.latitude;
	}

	/**
	 * 纬度.
	 * @param latitude
	 */
	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	/**
	 * .
	 * @return
	 */
	public String getCreatorId() {
		return this.creatorId;
	}

	/**
	 * .
	 * @param creatorId
	 */
	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	/**
	 * .
	 * @return
	 */
	public String getCreator() {
		return this.creator;
	}

	/**
	 * .
	 * @param creator
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * .
	 * @return
	 */
	public String getCreateDate() {
		return this.createDate;
	}

	/**
	 * .
	 * @param createDate
	 */
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	/**
	 * .
	 * @return
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * .
	 * @param createTime
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * .
	 * @return
	 */
	public String getRemark() {
		return this.remark;
	}

	/**
	 * .
	 * @param remark
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getProvincePid() {
		return provincePid;
	}

	public void setProvincePid(String provincePid) {
		this.provincePid = provincePid;
	}

}