/**
 * 福建博思软件 1997-2018 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Fri Jan 12 18:51:41 CST 2018
 */
package com.bosssoft.egov.asset.drc.service;

import java.util.List;

import com.bosssoft.egov.asset.drc.entity.DrcAuthMenuUser;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.common.lang.data.Searcher;



/**
 * 用户对应角色不显示菜单信息表Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2018-01-12   xiedeshou　　　新建
 * </pre>
 */
public interface DrcAuthMenuUserService {

/**
	 * 增加用户对应角色不显示菜单信息表.
	 * 
	 * @param drcAuthMenuUser 用户对应角色不显示菜单信息表
	 */
	public void addDrcAuthMenuUser(DrcAuthMenuUser drcAuthMenuUser);

	/**
	 * 删除用户对应角色不显示菜单信息表及相关信息.
	 * 
	 * @param drcAuthMenuUser 用户对应角色不显示菜单信息表
	 */
	public void delDrcAuthMenuUser(DrcAuthMenuUser drcAuthMenuUser);

	/**
	 * 修改用户对应角色不显示菜单信息表.
	 * 
	 * @param drcAuthMenuUser 用户对应角色不显示菜单信息表
	 */
	public void updateDrcAuthMenuUser(DrcAuthMenuUser drcAuthMenuUser);

	/**
	 * 获取用户对应角色不显示菜单信息表列表.
	 * 
	 */
	public List<DrcAuthMenuUser> getDrcAuthMenuUserList(DrcAuthMenuUser drcAuthMenuUser);




   	/**
	 * 获取用户对应角色不显示菜单信息表分页.
	 * 
		 */
	public Page<DrcAuthMenuUser> queryDrcAuthMenuUserPage(Searcher searcher, Page<DrcAuthMenuUser> page);
			
    
}
 