/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sun Apr 09 09:47:27 CST 2017
 */
package com.bosssoft.egov.asset.amc.user.entity;
import javax.persistence.Column;
import javax.persistence.Table;

/**
 * 对象.
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-04-09   Administrator　　　新建
 * </pre>
 */
@Table(name = "DRC_AUTH_RULE_NEW")
public class DrcAuthRuleNew implements java.io.Serializable {

	private static final long serialVersionUID = 170409094854245L;
	
	// Fields
	
	/**
	 * .
	 */
    @Column(name = "ID")
	private Long id;
	/**
	 * .
	 */
    @Column(name = "CFG_ID")
	private Long cfgId;
	/**
	 * .
	 */
    @Column(name = "PARTY_ID")
	private String partyId;
	/**
	 * .
	 */
    @Column(name = "PARTY_TYPE")
	private String partyType;
	/**
	 * .
	 */
    @Column(name = "RULE_TYPE")
	private String ruleType;
	/**
	 * .
	 */
    @Column(name = "RULE_FIELD")
	private String ruleField;
	/**
	 * .
	 */
    @Column(name = "RULE_VALUE")
	private String ruleValue;
	/**
	 * .
	 */
    @Column(name = "RULE_OPERATOR")
	private String ruleOperator;
	/**
	 * .
	 */
    @Column(name = "RULE_CONDITION")
	private String ruleCondition;
	/**
	 * .
	 */
    @Column(name = "STATUS")
	private String status;
	/**
	 * .
	 */
    @Column(name = "REMARK")
	private String remark;
	/**
	 * .
	 */
    @Column(name = "PARTY_CODE")
	private String partyCode;
	/**
	 * .
	 */
    @Column(name = "PARTY_NAME")
	private String partyName;
	/**
	 * .
	 */
    @Column(name = "RULE_VALUE_ID")
	private Long ruleValueId;
	/**
	 * .
	 */
    @Column(name = "RULE_VALUE_CODE")
	private String ruleValueCode;
	/**
	 * .
	 */
    @Column(name = "RULE_VALUE_NAME")
	private String ruleValueName;
	/**
	 * .
	 */
    @Column(name = "RGN_ID")
	private Long rgnId;
	/**
	 * .
	 */
    @Column(name = "RGN_CODE")
	private String rgnCode;
	/**
	 * .
	 */
    @Column(name = "RGN_NAME")
	private String rgnName;
	/**
	 * .
	 */
    @Column(name = "ROLE_ID")
	private String roleId;
	/**
	 * .
	 */
    @Column(name = "ROLE_CODE")
	private String roleCode;
	/**
	 * .
	 */
    @Column(name = "ROLE_NAME")
	private String roleName;
	/**
	 * .
	 */
    @Column(name = "ROLE_TYPE")
	private String roleType;
	
	// Constructors
 
    /** default constructor */
	public DrcAuthRuleNew() {
	}

	/**
	 * .
	 * @return
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * .
	 * @param id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * .
	 * @return
	 */
	public Long getCfgId() {
		return this.cfgId;
	}

	/**
	 * .
	 * @param cfgId
	 */
	public void setCfgId(Long cfgId) {
		this.cfgId = cfgId;
	}

	/**
	 * .
	 * @return
	 */
	public String getPartyId() {
		return this.partyId;
	}

	/**
	 * .
	 * @param partyId
	 */
	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	/**
	 * .
	 * @return
	 */
	public String getPartyType() {
		return this.partyType;
	}

	/**
	 * .
	 * @param partyType
	 */
	public void setPartyType(String partyType) {
		this.partyType = partyType;
	}

	/**
	 * .
	 * @return
	 */
	public String getRuleType() {
		return this.ruleType;
	}

	/**
	 * .
	 * @param ruleType
	 */
	public void setRuleType(String ruleType) {
		this.ruleType = ruleType;
	}

	/**
	 * .
	 * @return
	 */
	public String getRuleField() {
		return this.ruleField;
	}

	/**
	 * .
	 * @param ruleField
	 */
	public void setRuleField(String ruleField) {
		this.ruleField = ruleField;
	}

	/**
	 * .
	 * @return
	 */
	public String getRuleValue() {
		return this.ruleValue;
	}

	/**
	 * .
	 * @param ruleValue
	 */
	public void setRuleValue(String ruleValue) {
		this.ruleValue = ruleValue;
	}

	/**
	 * .
	 * @return
	 */
	public String getRuleOperator() {
		return this.ruleOperator;
	}

	/**
	 * .
	 * @param ruleOperator
	 */
	public void setRuleOperator(String ruleOperator) {
		this.ruleOperator = ruleOperator;
	}

	/**
	 * .
	 * @return
	 */
	public String getRuleCondition() {
		return this.ruleCondition;
	}

	/**
	 * .
	 * @param ruleCondition
	 */
	public void setRuleCondition(String ruleCondition) {
		this.ruleCondition = ruleCondition;
	}

	/**
	 * .
	 * @return
	 */
	public String getStatus() {
		return this.status;
	}

	/**
	 * .
	 * @param status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * .
	 * @return
	 */
	public String getRemark() {
		return this.remark;
	}

	/**
	 * .
	 * @param remark
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * .
	 * @return
	 */
	public String getPartyCode() {
		return this.partyCode;
	}

	/**
	 * .
	 * @param partyCode
	 */
	public void setPartyCode(String partyCode) {
		this.partyCode = partyCode;
	}

	/**
	 * .
	 * @return
	 */
	public String getPartyName() {
		return this.partyName;
	}

	/**
	 * .
	 * @param partyName
	 */
	public void setPartyName(String partyName) {
		this.partyName = partyName;
	}

	/**
	 * .
	 * @return
	 */
	public Long getRuleValueId() {
		return this.ruleValueId;
	}

	/**
	 * .
	 * @param ruleValueId
	 */
	public void setRuleValueId(Long ruleValueId) {
		this.ruleValueId = ruleValueId;
	}

	/**
	 * .
	 * @return
	 */
	public String getRuleValueCode() {
		return this.ruleValueCode;
	}

	/**
	 * .
	 * @param ruleValueCode
	 */
	public void setRuleValueCode(String ruleValueCode) {
		this.ruleValueCode = ruleValueCode;
	}

	/**
	 * .
	 * @return
	 */
	public String getRuleValueName() {
		return this.ruleValueName;
	}

	/**
	 * .
	 * @param ruleValueName
	 */
	public void setRuleValueName(String ruleValueName) {
		this.ruleValueName = ruleValueName;
	}

	/**
	 * .
	 * @return
	 */
	public Long getRgnId() {
		return this.rgnId;
	}

	/**
	 * .
	 * @param rgnId
	 */
	public void setRgnId(Long rgnId) {
		this.rgnId = rgnId;
	}

	/**
	 * .
	 * @return
	 */
	public String getRgnCode() {
		return this.rgnCode;
	}

	/**
	 * .
	 * @param rgnCode
	 */
	public void setRgnCode(String rgnCode) {
		this.rgnCode = rgnCode;
	}

	/**
	 * .
	 * @return
	 */
	public String getRgnName() {
		return this.rgnName;
	}

	/**
	 * .
	 * @param rgnName
	 */
	public void setRgnName(String rgnName) {
		this.rgnName = rgnName;
	}

	/**
	 * .
	 * @return
	 */
	public String getRoleId() {
		return this.roleId;
	}

	/**
	 * .
	 * @param roleId
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * .
	 * @return
	 */
	public String getRoleCode() {
		return this.roleCode;
	}

	/**
	 * .
	 * @param roleCode
	 */
	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	/**
	 * .
	 * @return
	 */
	public String getRoleName() {
		return this.roleName;
	}

	/**
	 * .
	 * @param roleName
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * .
	 * @return
	 */
	public String getRoleType() {
		return this.roleType;
	}

	/**
	 * .
	 * @param roleType
	 */
	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

}