/*******************************************************************************
 * 福建博思软件1997-2017 版权所有
 * 
 * Auto generated by Bosssoft Studio version 1.0 beta
 * 2018年1月26日下午3:08:51
 *******************************************************************************/
package com.bosssoft.egov.asset.skin.cache.cacheloader;

import java.io.Serializable;
import java.util.Map;

import javax.annotation.Resource;

import com.bosssoft.egov.asset.skin.entiry.AssetSkinCfg;
import com.bosssoft.egov.asset.skin.mapper.AssetSkinCfgMapper;
import com.bosssoft.platform.cache.api.Cache;
import com.bosssoft.platform.cache.api.CacheLoader;

/**
 * @ClassName	类名：AssetSkinCacheLoader.java
 * @Description	功能说明：用户皮肤缓存加载器
 * <pre>
 * @date		创建日期：2018年1月26日
 * @author		创建人：chenzhibin
 * @version		版本号：V1.0
 * <pre>
 *-------------------修订记录---------------------
 */
public class AssetSkinCacheLoader implements CacheLoader {
	
	@Resource
	private AssetSkinCfgMapper skinCfgMapper;

	@Override
	public Map<Serializable, Serializable> preLoad(Cache cache) {
		return null;
	}

	@Override
	public Serializable get(Serializable key) {
		String lookupKey = (String) key;
		String[] keys = lookupKey.split("::");
		AssetSkinCfg skin;
		
		try{
			skin = skinCfgMapper.getSkinCfgByUserCode(keys[1]);
		} catch(Exception e){
			skin = null;
		}
		return skin;
	}

	@Override
	public void put(Serializable key, Serializable value) {
		AssetSkinCfg skin = (AssetSkinCfg) value;
		skinCfgMapper.insertSelective(skin);
	}

	@Override
	public Serializable remove(Serializable key) {
		String lookupKey = (String) key;
		String[] keys = lookupKey.split("::");
		
		return skinCfgMapper.deleteSkinCfgByUserCode(keys[1]);
	}

}
