/**
 * 福建博思软件 1997-2017 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Thu Mar 09 01:43:53 CST 2017
 */
package com.bosssoft.egov.connect.mapper;

import org.apache.ibatis.annotations.Param;
import com.bosssoft.egov.connect.entity.RecycleOrg;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.persistence.common.Mapper;
import com.bosssoft.platform.common.lang.data.Searcher;
import com.bosssoft.platform.runtime.exception.BusinessException;

/**
 * 类说明:  Mapper接口（ Mapper层） .
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2017-03-09   Administrator　　　新建
 * </pre>

 */

public interface RecycleOrgMapper extends Mapper<RecycleOrg>{



/**
	 * 
	 * 查询分页.
	 *	`
	 * @param searcher 查询条件
	 * @param pageable 分页信息
	 * @return RecycleOrgPage列表
	 * @throws BusinessException 自定义异常
	 *
	 */
	public Page<RecycleOrg> queryRecycleOrgPage(@Param("searcher")Searcher searcher,@Param("page")Page<RecycleOrg> page);
			
	/**
	 * <p>函数名称：updateById        </p>
	 * <p>功能说明：根据id修改回收机构信息
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param recycleOrg
	 *
	 * @date   创建时间：2017年9月30日
	 * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
	 */
	public void updateById(RecycleOrg recycleOrg);
	
	/**
	 * <p>函数名称：deletebyId        </p>
	 * <p>功能说明：根据id删除回收机构信息
	 *
	 * </p>
	 *<p>参数说明：</p>
	 * @param recycleOrg
	 *
	 * @date   创建时间：2017年9月30日
	 * @author 作者：黄振雄 (mailto:huangzhenxiong@bosssoft.com.cn)
	 */
	public void deletebyId(RecycleOrg recycleOrg);

}